otter-blocks.php, package.json
- Adds Feedback for Button Group Switch
- Fixes Post Grid throwing an error
- Fixes issue with multiple block templates being inserted on the same post
- Fixes Font Awesome block alignment on the backend
=> Release 1.1.3

otter-blocks.php, package.json, readme.md, readme.txt
- Redesign Template Library
- Added Dynamic Column Resizing
- Added option to Auto Display Columns on Pages
- Added Section Outline to make it easier to edit sections
- Added Hover and Link settings to Font Awesome Block
- Removed Google + icon from Sharing Icons Block
- Fixed alignment controls
- Fixed issue with non-editors not being able to use inline CSS and template library.
- Fixed Button Group errors
- Fixed Sharing Icons block having wrong icon order in front-end
=> Release 1.1.5

class-otter-blocks.php, composer.lock, package-lock.json, package.json
- Fix Button Group Block borders
- Fix Plugin Card failing with additional attributes
- Fix permission callback missing in REST API Route
=> Release 1.5.7

composer.lock, readme.md, readme.txt
- Do not add the background image to the Section when the URL is not set.
=> Release: 1.5.11

composer.lock, package-lock.json
- Fix Columns range crashing in Section Block.
- Fix Progress Blocks not loading on front-end.
=> Version 1.6.3

inc/class-main.php
Fix #600
How to test: pust some block, preview it. If nothing special is happening and all of them are working, it is considered fixed.
=> Add missing arguments in function call from `main`

inc/class-main.php, inc/plugins/class-block-conditions.php, package-lock.json, src/blocks/plugins/conditions/edit.js
Based on https://github.com/Codeinwp/otter-blocks/issues/561
=> Add More Conditions

inc/css/blocks/class-icon-list-css.php, src/blocks/blocks/icon-list/attributes.js, src/blocks/blocks/icon-list/controls.js, src/blocks/blocks/icon-list/edit.js, src/blocks/blocks/icon-list/editor.scss, src/blocks/blocks/icon-list/inspector.js, src/blocks/blocks/icon-list/style.scss
=> Icon List Improvements

.gitattributes, webpack.config.js
Changelog:
- Remove `sourceMap` from bulid files
- Ignore `.vscode` folder
Fix #603
=> Reduce build files size.

inc/css/class-block-frontend.php
Changelog:
- change `themeisle-block_styles` with `otter-blocks`
=> Update PHP dependancy function

inc/css/blocks/class-flip-css.php, src/blocks/blocks/flip/edit.js, src/blocks/blocks/flip/save.js, src/blocks/blocks/flip/style.scss
Add `o-flip` prefix on all CSS classes for Flip
=> Flip CSS refactor

inc/render/class-review-block.php, src/blocks/blocks/review/style.scss
Fix #638
Just a CSS update. There sould be no breaking change!
=> Remove CLS from featured image in Review

src/animation/frontend.js
- Use `addEventListener` for loading
- Increase detection range
=> Animation module fix

inc/css/blocks/class-flip-css.php, src/blocks/blocks/flip/attributes.js, src/blocks/blocks/flip/edit.js, src/blocks/blocks/flip/inspector.js, src/blocks/blocks/flip/save.js
- Fix the wrong class name on the `save` function
- Fix alignment 
⚠️ Those are breaking changes.
=> Flip Card Fix

inc/render/class-google-map-block.php, src/blocks/blocks/accordion/style.scss
Close #632
This is just a CSS update. The should be no breaking changes.
:warning: This is Windows/Linux bug. Test with a Windows/Linux OS. You can try Browserstack.
P.S: Fixing weird CSS bug is making me belive in Magic ヾ(•ω•`)o
=> Fix emoji in Accordion Block

docs/index.md, docs/testing-cheatsheet.md
Add docs with snipped code for testing.
Features
- Insert all blocks
- Insert blocks that are not using Neve or Neve Pro to work
- Insert blocks that use Neve or Neve Pro to work or to unlock features
=> Christmas Gift for QA team

composer.json, inc/class-main.php, inc/render/class-masonry-variant.php, src/blocks/frontend/masonry/index.js, src/blocks/plugins/galley-extension/index.js, src/blocks/plugins/masonry-extension/edit.js, src/blocks/plugins/masonry-extension/index.js
This PR will fix the Masonry for the new Gallery in WP 5.9 but is not backward compatible!
=> Fix Masonry for WP 5.9

inc/class-base-css.php, inc/css/blocks/class-advanced-column-css.php, inc/css/blocks/class-advanced-columns-css.php
=> URL validation for images

src/blocks/blocks/tabs/editor.scss, src/blocks/blocks/tabs/style.scss, src/blocks/frontend/tabs/index.js
=> Fix Tabs scoping

package-lock.json, package.json
Reverts Codeinwp/otter-blocks#701
=> Revert "Bump @wordpress/scripts from 19.2.2 to 20.0.2"

package-lock.json, package.json
Reverts Codeinwp/otter-blocks#705
=> Revert "Bump react-notifications-component from 3.1.0 to 3.3.11"

src/blocks/blocks/icon-list/style.scss
FIx #714 
There should be no breaking changes!
=> Remove `font-size` CSS from Icon List

inc/css/blocks/class-advanced-columns-css.php
=> Fix Section overlay regression

src/blocks/plugins/sticky/edit.js
Lock the UI for non-Pro users.
Ref: https://github.com/Codeinwp/otter-blocks/issues/751
=> Add Pro restrictions to Sticky

inc/plugins/class-block-conditions.php, src/blocks/plugins/conditions/edit.js
Added a new condition based on how much the user spent.
Uses the WooComerce function `get_total_spent()`.
=> New visibility condition based on how much the user spent during lifetime

inc/class-blocks-animation.php
=> fix: use the correct path

src/blocks/helpers/helper-functions.js
=> Add translations for countdown

inc/css/blocks/class-advanced-column-css.php, inc/css/blocks/class-advanced-columns-css.php
Copy of: https://github.com/Codeinwp/otter-blocks/pull/827
=> padding and margins

inc/css/blocks/class-accordion-css.php, inc/css/blocks/class-advanced-column-css.php, inc/css/blocks/class-advanced-columns-css.php, inc/css/blocks/class-font-awesome-icons-css.php, inc/css/blocks/class-review-css.php, src/blocks/blocks/section/column/deprecated.js, src/blocks/blocks/section/columns/deprecated.js, src/blocks/helpers/helper-functions.js
Can you check @mghenciu if the issue is still there with this?
=> Fix zero padding/margin not migrating

src/blocks/blocks/tabs/group/edit.js, src/blocks/blocks/tabs/group/inspector.js, src/blocks/blocks/tabs/item/block.json, src/blocks/blocks/tabs/item/edit.js, src/blocks/blocks/tabs/item/inspector.js, src/blocks/blocks/tabs/item/save.js, src/blocks/frontend/tabs/index.js
Adds a select control for choosing which tab is open by default.
=> Default open tab

src/animation/data.js
Removed the option to select out animations.
I kept some of the code for the out animations so that the sites that are using them won't break.
=> Remove out animations

src/blocks/blocks/posts/editor.scss, src/blocks/blocks/posts/style.scss
Made Posts Block responsive on mobile.
Closes #844.
=> Fix: responsive posts block

src/blocks/blocks/flip/block.json, src/blocks/blocks/flip/edit.js
Fixes #913 
----
Insert a Flip Card, and make sure the `border-width` & `border-radius` can be 0. Save the page, refresh and check if the values are saved.
=> Fix Flip Card

src/blocks/blocks/posts/components/sortable.js
Fixes https://github.com/Codeinwp/otter-blocks/issues/925
=> Fix Posts Excerpt not saving

src/blocks/plugins/css-handler/index.js
Fixes #896 
By adding the id, the snack bar will be reused.
=> Reuse the snack bar on saving.

src/blocks/blocks/sharing-icons/inspector.js
Further improvements from https://github.com/Codeinwp/otter-blocks/pull/873
=> Sharing Icons

src/blocks/blocks/posts/components/sortable.js, src/blocks/global.d.ts
Remove obsolete option that blocks the custom fields from displaying in Inspector.
=> Fix custom ACF fields not showing

src/blocks/blocks/accordion/style.scss
Closes #932 
----
Create an Accordion block. Insert a very long text in the title: 
```
<strong>Lorem Ipsum is simply dummy text </strong> of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
```
Before: 
Now:
=> Change the structure of the accordion title

src/blocks/frontend/masonry/index.js
Fixes #784 
Add breakpoints for mobile and tablets.
=> Make Masonry responsive

inc/class-registration.php, inc/render/class-masonry-variant.php, src/blocks/blocks/slider/edit.js, src/blocks/blocks/slider/transforms.js, src/blocks/global.d.ts, src/blocks/plugins/galley-extension/index.js, src/blocks/plugins/masonry-extension-old/edit.js
Closes #931
----
Create a gallery. Try to convert it to the slider, then back to the gallery.
=> Update slider transform function

inc/class-pro.php, otter-blocks.php, src/animation/count/index.js, src/animation/typing/index.js, src/blocks/blocks/posts/components/design-layout-builder.js, src/blocks/plugins/dynamic-content/components/fields.js, src/blocks/plugins/dynamic-content/components/inline-controls.js, src/blocks/plugins/dynamic-content/index.js, src/blocks/plugins/sticky/edit.js, src/dashboard/components/pages/Upsell.js, src/dashboard/style.scss, src/pro/plugins/posts/index.js, src/pro/plugins/sticky/index.js
Closes https://github.com/Codeinwp/otter-internals/issues/23.
Addressing upsell points from the mentioned PR.
=> Feature visibility

.github/workflows/create-build-url.yml
Closes #.
This is a work in progress:
- Use the actual InstaWP action.
- Use the main otter-qa website for wporg benchmark instead of making a new one.
----
----
=> Add Github Action

readme.txt, src/dashboard/components/Sidebar.js, src/dashboard/style.scss
=> Doc link in readme and links in the Dashboard

src/blocks/helpers/helper-functions.js
Closes #1194.
Add checking for a default value.
----
1. Create a Section
2. Go to Tablet/Mobile
3. Add a value to padding.
----
=> Fix undefined value check.

src/blocks/blocks/countdown/inspector.js, src/blocks/blocks/lottie/inspector.js, src/blocks/components/icon-picker-control/index.js, src/pro/plugins/countdown/index.tsx
=> Ongoing 6.1 Beta Fixes

inc/class-pro.php
=> Fix BF deal not dismissing

inc/css/blocks/class-review-css.php, inc/render/class-review-block.php, src/blocks/blocks/review/block.json, src/blocks/blocks/review/edit.js, src/blocks/blocks/review/editor.scss, src/blocks/blocks/review/inspector.js, src/blocks/blocks/review/style.scss, src/blocks/blocks/review/type.d.ts
Closes #1260.
Add a description for each feature of the product in the Review Block, under the review.
----
- In the `Product Features` panel, when a feature is clicked, the text area for the description should appear under the `rating` control.
- It will inherit the text color, and will have `0.7 opacity` and `80% font size` of the feature title font size (which is the content font size)
- we need to make sure it looks ok with both styles (One Column and Two Columns)
----
=> Add description for each feature in the review block

src/blocks/frontend/sticky/index.ts
Closes #866.
- Add recalculation for Sticky triggers for the edge case when dynamic height blocks (Tabs, Accordion) are present on the page.
----
There might be some edge cases, but this must work for simple cases like a Sticky block after a tab or accordion.
Below is an example.
```html
<div id="wp-block-themeisle-blocks-tabs-1b9656a0" class="wp-block-themeisle-blocks-tabs"><div class="wp-block-themeisle-blocks-tabs__content">
<div data-title="Small Tab" class="wp-block-themeisle-blocks-tabs-item"><div class="wp-block-themeisle-blocks-tabs-item__header" tabindex="0">Small Tab</div><div class="wp-block-themeisle-blocks-tabs-item__content">
<p>Lorem ipsum dolor sit amet netus eu egestas elementum dictum taciti. Fusce id curae maecenas cubilia vivamus. Semper elit si lectus convallis …
```
=> Resolve Sticky conflict with Tabs, Accordion Block

inc/server/class-dynamic-content-server.php
Master base for https://github.com/Codeinwp/otter-blocks/pull/1631#pullrequestreview-1401801600
=> Dynamic content fallback sanitization

inc/class-blocks-css.php
Closes #1614 .
The Custom CSS wasn't working in template parts on FSE themes when using only the Blocks CSS child plugin.
The steps are described really well in the issue, so I'm gonna copy some of them here:
- Install and activate only the Blocks CSS plugin and a FSE theme
- Go to wordpress appearance -> editor -> template parts -> header
- Insert a search block into the header
- Write some custom CSS for the block, for example:
```css
.wp-block-search__inside-wrapper {
border-width: 1px !important;
border-style: solid !important;
background: burlywood;
}
```
- See the block's CSS update live in the editor
- Save the header and the CSS should be applied also in the frontend
Edit by Hardeep: Make sure to test it with both Otter and Blocks CSS separately and together.
----
=> fix: custom css in template parts

inc/plugins/class-dashboard.php
Closes #.
Add form submissions dashboard on the Admin page.
ℹ️ Some discussions with @mghenciu have been made to tweak the aspect.
ℹ️ If the submission has an Email type field, that value will be used instead of Submission ID.
ℹ️ When you change the filter, the page will reload. We are using PHP for getting the posts.
ℹ️ If the user has a Form registered, it will appear in the widget.
https://github.com/Codeinwp/otter-blocks/assets/17597852/63922bde-71e7-4dab-a7be-cc802569092d
----
⚠️ The widget will appear to all who have at least one widget registered (it does not count if it is still present or not -- practically if the user has used it at least once in the Form). On a fresh WP instance, the widget should not be present.
1. Go to the Admin page and see the Submissions widget.
2. Play …
=> Add form submissions dashboard

inc/server/class-dynamic-content-server.php, plugins/otter-pro/inc/server/class-filter-blocks-server.php
Closes #1764.
Fixed remaining PHPStan issues.
Test `Review Comparision Table` block. It can be the only one that could possibly have an issue. 
----
=> Fix phpstan small issues

readme.md, readme.txt
Optimized the tags and formating of the content for better SEO
N/A
----
N/A
----
=> updated readme

readme.txt
Added Stripe checkout content
Added AI block content
Minor format changes
Minor content addition
Closes #.
----
----
=> added ai block content

plugins/blocks-animation/readme.md, plugins/blocks-animation/readme.txt, plugins/blocks-css/readme.md, plugins/blocks-css/readme.txt, plugins/blocks-export-import/readme.md, plugins/blocks-export-import/readme.txt, readme.md, readme.txt
Update WP tested version to 6.4 as no issues were found
=> chore: update wp tested version

readme.txt
=> Added new screenshots

src/css/inject-css.js
Closes #2056.
This fixes the issue with Blocks CSS updating reusable blocks with every typing event.
----
You can follow the reproduction steps defined in the issue and confirm the console notice doesn't appear anymore.
----
=> fix: blocks css performance

src/onboarding/components/Main.js, src/onboarding/components/Sidebar.js, src/onboarding/hooks/index.js
=> fix: improvements to onboarding loading

src/blocks/plugins/patterns-library/cloudLibraryPlaceholder.js
=> updated description for clarity

bin/dist.sh, plugins/blocks-animation/readme.md, plugins/blocks-animation/readme.txt, plugins/blocks-css/readme.md, plugins/blocks-css/readme.txt, plugins/blocks-export-import/readme.md, plugins/blocks-export-import/readme.txt
Closes https://github.com/Codeinwp/otter-internals/issues/247#event-17766204235
Include the repository link for the source files in Animation, CSS & Export-Import plugins.
~Include the source files for Animation, CSS & Export-Import plugins.~
----
----
=> dev: include repository link for source files
