Codeinwp/otter-blocks

- inc/css/blocks/class-advanced-heading-css.php
- src/blocks/blocks/advanced-heading/attributes.js
- src/blocks/blocks/advanced-heading/controls.js
- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/blocks/advanced-heading/editor.scss
- src/blocks/blocks/advanced-heading/inspector.js
- src/blocks/components/clear-button/editor.scss
- src/blocks/components/clear-button/index.js
Changelog:
This PR will introduce a new component: `ClearButton` which will reset the given attributes to `undefined`. It has a similar logic with `classnames` when it comes to arguments.
E.g.:
https://github.com/Codeinwp/otter-blocks/blob/8d8509be04e9bfbf75527db166c590de9561429d/src/blocks/blocks/advanced-heading/inspector.js#L488-L491
https://github.com/Codeinwp/otter-blocks/blob/8d8509be04e9bfbf75527db166c590de9561429d/src/blocks/blocks/advanced-heading/inspector.js#L520-L523
https://github.com/Codeinwp/otter-blocks/blob/8d8509be04e9bfbf75527db166c590de9561429d/src/blocks/blocks/advanced-heading/inspector.js#L733-L746
> Improve Advance Heading Controls

- inc/css/blocks/class-button-group-css.php
- src/blocks/blocks/button-group/button/edit.js
- src/blocks/blocks/button-group/editor.scss
- src/blocks/blocks/button-group/group/edit.js
Fix #544
This PR will only change the styling in PHP and Editor.
Testing: No breaking changes should arise. Put a group with buttons of different sizes, go to mobile mode and reduce the window width until the buttons are vertical. They should be centered; if not, the problem is still present.
| Wrong |![image](https://user-images.githubusercontent.com/17597852/141483000-dc1f5d2d-d3d6-42e8-b9a9-b3f55f3303d2.png) | 
| ---- | --- |
| Correct | ![image](https://user-images.githubusercontent.com/17597852/141482844-83c0a46e-6d87-4ce8-a0d9-5ffafa736420.png)|
> Refactor the group button spacing

- inc/class-main.php
- src/blocks/blocks/form/edit.js
- src/blocks/plugins/css-handler/index.js
- src/blocks/plugins/data-logging/index.js
- src/blocks/plugins/registerPlugin.js
Make sure core/editor package doesn't cause any issues on the widgets screen.
@irinelenache Can you make sure of two things:
- Blocks load properly in Post Editor.
- Blocks load properly in Widget screen while this plugin is installed: https://wordpress.org/plugins/download-monitor/
Closes #605
> Add additional checks on core/editor loading

- src/blocks/blocks/font-awesome-icons/editor.scss
- src/blocks/blocks/font-awesome-icons/style.scss
Fix #618 
Use this for testing:
```html
<div class="wp-block-group">
<p class="wp-block-themeisle-blocks-font-awesome-icons" id="wp-block-themeisle-blocks-font-awesome-icons-2fc2eb9d"><span class="wp-block-themeisle-blocks-font-awesome-icons-container"><i class="fab fa-accusoft"></i></span></p>
<h3 id="professional">PROFESSIONAL</h3>
<p>Butcher austin biodiesel aesthetic cray palo santo la croix gastropub forage. Seitan lo-fi minim, poke duis kale chips</p>
</div>
```
Use the `development` branch, create a new post and paste the code above. Preview it; the icon should be a little to the left, like in the issue. 
After switching to this, the icon will respect the container, and there should be no breaking changes.
> Icon visual fix

- inc/css/blocks/class-icon-list-css.php
- src/blocks/blocks/icon-list/edit.js
- src/blocks/blocks/icon-list/inspector.js
- src/blocks/blocks/icon-list/item/edit.js
- src/blocks/blocks/icon-list/style.scss
Fix #621
Changelog:
- Use `gap` instead of `margin` for spacing
- Add reset button to `font-size` and `gap`
- Move defaults value to CSS instead of PHP
Like in #611, this is just styling and no breaking change should be present.
> Refactor spacing in Icon List Block

- inc/class-blocks-animation.php
- inc/class-blocks-css.php
- inc/class-main.php
This fixes Blocks CSS not working. Closes https://github.com/Codeinwp/otter-blocks/issues/631
To test, make sure:
- Blocks CSS work properly on Otter & non-Otter blocks.
- Make sure this change doesn't break Block Conditions and they keep working.
Can you do the testing @irinelenache?
> Fix Blocks CSS not working

- src/blocks/blocks/section/columns/inspector.js
The user can not select a `width` more than `1200px` even though the max is `1800px`.
> fix(section): bump width to 2400px

- src/animation/editor.js
- src/css/index.js
Disable custom CSS editor for Site Editor: https://github.com/Codeinwp/otter-blocks/issues/671
Animations work just fine but without the animations being previewed.
> Disable custom CSS for Site Editor

- src/blocks/blocks/popup/save.js
This should fix it: https://github.com/Codeinwp/otter-blocks/issues/657
> Fix pop not working with WP 5.9

- src/blocks/plugins/masonry-extension/edit.js
- src/blocks/plugins/masonry-extension/index.js
- Add a new condition such as not adding Masonry when images are loading.
- Make `Edit` be more like a wrapper.
> Fix image duplication for Masonry Plugin

- inc/render/class-woo-comparison-block.php
Comparison table block styles wasn't working on the editor side (ref: https://github.com/Codeinwp/otter-blocks/issues/657#issuecomment-1022141070 reported by @irinelenache)
Now, comparison table block styles works well frontend+editor side.
Note: To able fix the issue; this PR needs a dependent PR on Neve Pro repo: https://github.com/Codeinwp/neve-pro-addon/pull/1834
1. Install Otter from this PR: https://github.com/Codeinwp/otter-blocks/pull/691
2. Install Neve Pro from this PR: https://github.com/Codeinwp/neve-pro-addon/pull/1834
3. Comparison Table block should be worked well on frontend+editor side.
cc: @Soare-Robert-Daniel
> fix: comparison table editor style

- src/blocks/blocks/section/columns/inspector.js
Added a reset button for the range that controls the maximal content width on sections.
When clicked it sets the value to the default value which is `undefined`.
> Add reset button for section width range control

- src/animation/editor.scss
Makes animated blocks show when the page is printed.
> Fix: animations on print

- inc/render/class-about-author-block.php
- src/blocks/blocks/about-author/style.scss
Improvements on the About Author block:
- fixed text color on Neve dark mode
- author's name is centered when the description is empty
> Fix: About author block on dark mode

- src/blocks/blocks/google-map/edit.js
- src/blocks/blocks/google-map/editor.scss
- src/blocks/blocks/google-map/placeholder.js
When the saved API key is invalid, the placeholder should appear instead of the blank map.
If the user enters again an invalid key the issue is still there, but after a refresh, the placeholder should appear again.
So, the issue is partially solved.
> Fix: Google maps invalid key

- inc/class-registration.php
- inc/plugins/class-block-conditions.php
- inc/plugins/class-options-settings.php
- src/blocks/plugins/conditions/index.js
- src/dashboard/Components/Main.js
fixes: https://github.com/Codeinwp/otter-blocks/issues/838
There should be an option to disable the module in Dashboard.
>  Allow option to disable Block Conditions module

- src/animation/frontend/typing/index.js
Fix #845
---- 
```javascript
new QueryQA().select('blocks').where({ has: { plugins: ['typing'] }}).run()
```
[Query Engine](https://github.com/Codeinwp/otter-query-engine)  
[Browser Extension](https://github.com/Soare-Robert-Daniel/otter-blocks-qa-templates/tree/main/chrome-extension)
> Fix speed class name for Typing

- src/blocks/blocks/leaflet-map/edit.js
- src/blocks/frontend/leaflet-map/index.js
- src/blocks/helpers/block-utility.js
fix #869 
@HardeepAsrani, my method for detecting reusable blocks is pretty brute. I did not find a more reliable way to check if the block from the page is a reusable block. So, for now, I am checking if the block ID is in one of the reusable blocks provided by 
```javascript
select( 'core/block-editor' )
?.getSettings()
?.__experimentalReusableBlocks.
```
----
Create a simple Lottie block, make it a reusable block, then insert the reusable block on the page a few times, and check if the animation is still showing. Also, the page must not freeze.
Also, try to add a new Otter block to it while is duplicated. For duplicated reusable blocks, the changes are reflected. If we add a new block inside it, change the colors then *publish* the page, the colors need to work in the frontend. …
> Stop the infinit loop for Resuable Blocks on the ID hook.

- src/blocks/blocks/section/editor.scss
- src/blocks/blocks/section/style.scss
When `word-break: keep-all` is used it doesn't respect breaks in the flow of text for languages such as Chinese and Japanese.
This causes the text to "overflow" off the page:
As per MDN for `keep-all` value:
> Word breaks should not be used for Chinese/Japanese/Korean (CJK) text. Non-CJK text behavior is the same as for normal.
https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
Expected behavior introduced by this pull:
This was reported in Neve but this block is by Otter https://github.com/Codeinwp/neve-pro-addon/issues/1933
> fix: wrong word-break was not working for text without spaces

- src/blocks/blocks/section/style.scss
Fixes #878
----
Query
```javascript
new QueryQA().select('blocks').where({ names: ['one-column-section'] }).run()
```
> Fix ignored `max-width` for sections with one column

- src/blocks/blocks/section/columns/edit.js
- src/blocks/blocks/section/columns/inspector.js
Closes #980.
Removing columns with Toolbar will have the same behavior as removing them with the Inspector.
https://user-images.githubusercontent.com/17597852/174963343-418206b3-1c92-4398-90cc-3629bb834fe8.mp4
----
1. Insert a Section block.
2. Add/Remove block via Toolbar.
3. Check their width value.
You can see the clip on how it should look.
----
> Fix column remove via Toolbar

- src/blocks/blocks/flip/style.scss
Closes #883 .
The container of the Flip Card had full width regardless of the width of the card thus creating a bigger hover space than necessary.
- Place a Flip Card block in a container larger than the card
- The hover space should be exactly the size of the card
----
> Hover space on Flip Card

- src/blocks/frontend/tabs/index.js
Closes #991.
Fixes the issue where if a page had multiple tabs, only the first tab worked properly. Also, change the Untitled title to Tab `n`
----
- Add a multiple Tabs block to a page and make sure all of them work properly.
----
> Fix multiple tabs not working on same page

- inc/render/class-leaflet-map-block.php
- src/blocks/frontend/leaflet-map/index.js
Closes #785.
- Adds a gray background for the block until the map is loaded.
- The Google map already had this, so no need to modify anything there.
- It also fixes a jumping the page had when the map was loading because of the margin that appeared only when the map loaded (the block CSS doesn't load until the map loads).
Add a map block, and until the map loads, in the frontend should appear a gray placeholder.
----
> Add static background until map is loaded (for leaflet)

- src/blocks/blocks/advanced-heading/editor.scss
- src/blocks/blocks/advanced-heading/style.scss
Closes #1003.
Add missing import of the `style.scss`.
----
1. Insert an Adv Heading.
2. Set tag to Span.
3. Play with the alignment.
----
> Fix Adv Heading Span alignment

- src/blocks/plugins/conditions/edit.js
- src/pro/plugins/conditions/edit.js
- src/pro/plugins/data/index.js
Closes #799 .
The Condition Inspector is triggering for every block, thus any computation becomes expensive. This update will make sure that the data is done only when needed. Also, I suspect that the useSelect was doing synchronization with the global store, thus the _indirect_ overhead in the Profiler for `onStoreChange`.
@HardeepAsrani @selul @Skystream96 @preda-bogdan @abaicus feel free to take a look.
The site was tested with the following query: `new QueryQA().select('blocks').run()` which puts all the block template available (more than 70 blocks in total).
**Performance result**
Current version:
As you can see, a lot of red dots indicated a huge load with like a 100ms computation time per typing.
Updated: 
No more red dots. 30 ms computation time per typing. _So 3x increase in …
> Fix typing slowness

- inc/css/blocks/class-advanced-column-css.php
- inc/css/blocks/class-advanced-columns-css.php
- src/blocks/blocks/section/column/edit.js
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/block.json
- src/blocks/blocks/section/columns/edit.js
- src/blocks/blocks/section/columns/inspector.js
Closes #1030 .
Remove the strict scoping for some CSS props.
----
1. Insert a Section block
2. Customize on desktop
3. Check on the Mobile/Tablet preview to see if the CSS is kept.
4. Tablet/Mobile should inherit from Desktop. If Tablet is set, the Mobile will inherit them instead of the Desktop.
```javascript
new QueryQA().select('blocks').where({ has: { blocks: ['section'] }}).run()
```
----
> Made desktop the default style for Section block

- src/blocks/blocks/circle-counter/edit.js
- src/blocks/blocks/circle-counter/inspector.js
Closes #1051.
Remove automatic height adjustement that cause the font size to take huge values when the user break the Range component for height.
Code clean-up.
----
1. Insert A Circle Counter block.
2. Play with the Height option and see if the font-size breaks.
Video from the issue: https://www.loom.com/share/dc14e467f1fc4eb0a5b6fb8d92e666b4
----
> Remove Height automatic change on Circle Counter

- plugins/otter-pro/inc/plugins/class-block-conditions.php
- src/blocks/plugins/conditions/edit.js
- src/pro/plugins/conditions/edit.js
- src/pro/plugins/conditions/index.js
Closes #1020.
This adds a new condition to the module which enables you to display blocks based on the logged-in user's meta value.
----
- Check if different conditions of the meta work and how they react if the user is not logged-in.
----
> Add Logged-in user meta condition to Block Conditions module

- src/css/editor.js
- src/css/editor.scss
Closes #1007.
Add mechanism for detecting wrong CSS code.
----
----
> [WIP] Code checking for Custom CSS Editor

- inc/class-pro.php
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/inspector.js
Closes #1077.
Fix the usage of `merge` from Lodash since the first parameter will be changed, thus causing a bug that gives the Desktop the value from Mobile/Tablet.
Add box cleaning to default values (introduced in Countdown PR).
----
1. Insert a Section
2. Play with the padding/margin
----
> Fix Section responsive inheritance

- src/blocks/plugins/conditions/edit.js
Closes #999.
Add a notice to the user that the conditions might not be saved when used in Customizer.
----
1. Make a widget using an Otter block.
2. Go to Customizer
3. Select the block and go to Conditions
4. Check if the notice appears
----
> Fix Conditions when used in Customizer.

- inc/plugins/class-options-settings.php
- inc/render/class-review-block.php
- src/dashboard/components/pages/Dashboard.js
Closes #1092, #1072.
- Add option to disable schema
- Add Pros/Cons schema to Review Block
----
Make sure the Rich Schema option works properly, and Pros/Cons option passes Rich Schema test https://search.google.com/test/rich-results
----
> Product Review Block Enhancements

- src/blocks/blocks/icon-list/block.json
- src/blocks/blocks/icon-list/item/edit.js
- src/blocks/blocks/icon-list/types.d.ts
Closes #1083.
We had the wrong attribute name so the default icon in Font Awesome never worked if it was a brand icon. This should fix it.
----
It should really be tested to make sure things don't break when coming from past versions.
----
> Fix Icon List default icon not working

- src/blocks/blocks/countdown/inspector.js
- src/blocks/blocks/countdown/style.scss
Closes #1090.
Fix border selection and default value handling. Override some WP defaults.
----
----
> Fix countdown border

- src/blocks/components/background-selector-control/index.js
Closes #1093.
Fix ambiguous chaining that can show some unrelated color options when navigating back and forth.
----
1. Insert a Section color.
2. Set some background colors.
3. Switch between Color, Image, and Gradient continuously and check if Color options are not appearing in Gradient and vice versa
----
> Fix BackgroundSelectorControl

- src/blocks/blocks/countdown/style.scss
Closes #1107.
Some CSS names remained in their original form after the merge with the snake case CSS name PR.
----
1. Insert a countdown.
2. Play with the controls
----
> Clean up camel case name

- inc/class-base-css.php
> Fix animation issue with Reusable blocks

- src/blocks/blocks/button-group/group/inspector.js
- src/blocks/components/toogle-group-control/index.js
- src/blocks/components/toogle-group-control/type.d.ts
Closes #1078.
Remade the alignment selector to something that can work in FSE.
----
1. Insert a Button Group block
2. Check the Alignment in inspector
----
> Fix alignment selection for GroupButton in FSE

- inc/css/blocks/class-button-css.php
- package-lock.json
- package.json
- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/blocks/button-group/group/edit.js
- src/blocks/blocks/flip/style.scss
- src/blocks/blocks/icon-list/editor.scss
- src/blocks/blocks/progress-bar/style.scss
- src/blocks/components/google-fonts-control/index.js
Closes #1100.
Fix:
- Progress Bar outer percentage value position (which makes it look like there is a problem with the color)
- Missing fonts loader for Button Group
- Flip width
----
----
> Fixes for release 

- src/css/editor.js
- src/css/editor.scss
- src/css/inject-css.js
Closes #1116.
It fixes issues with custom CSS when the block already has an existing class. The bug was introduced only recently.
----
Make sure CSS works regardless if the block has one class, a million classes, or no class.
> Fix custom CSS not working if used with existing class

- src/blocks/blocks/about-author/index.js
Closes #1115.
If you're using WordPress version 5.9 or above, the About Author block will not appear in the Inserter. It'll work as normally before 5.8.
----
Make sure it appears in 5.8 and doesn't appear in 5.9 or above.
----
> Remove About Author Block from the Inserter

- src/blocks/plugins/dynamic-content/autocompleter.js
- src/blocks/plugins/dynamic-content/components/inline-controls.js
- src/blocks/plugins/dynamic-content/edit.js
- src/blocks/plugins/dynamic-content/editor.scss
- src/blocks/plugins/dynamic-content/media/media-content.js
- src/pro/plugins/dynamic-content/edit.js
Closes #1032.
It fixes:
- When using the `%` keyword with Otter free, show disabled Pro options in the end.
- Allow users to add dynamic tags even when no text is selected.
- Fix Spinner loading even when ACF fields are empty.
- Fix dynamic value breaking when you add and remove a custom meta.
----
Just make sure everything works as normal without any errors.
----
> Change sorting order in Dynamic Value

- inc/css/blocks/class-countdown-css.php
- src/blocks/blocks/countdown/block.json
- src/blocks/blocks/countdown/edit.js
- src/blocks/blocks/countdown/inspector.js
- src/blocks/blocks/countdown/style.scss
- src/blocks/blocks/countdown/types.d.ts
Closes #1109 .
Add alignment option for separators.
----
----
> Add alignment for separetors in Countdown

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/components/layout/featured.js
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/edit.js
Closes: https://github.com/Codeinwp/otter-blocks/issues/1122
All the instructions on how to reproduce issues are here: https://github.com/Codeinwp/otter-blocks/issues/1122
----
----
> Fix Category not working in Posts Block's featuerd section

- src/blocks/blocks/button-group/group/inspector.js
- src/blocks/components/toogle-group-control/editor.scss
- src/blocks/components/toogle-group-control/index.js
Closes #1123.
Add missing `?`.
----
----
> Add missing null checker for Alignment Toolbar Control

- inc/class-registration.php
Closes https://github.com/Codeinwp/otter-blocks/issues/1141.
It should make sure that the JS only loads when the block is being used + also in FSE.
> Fix js loading when not needed

- inc/css/blocks/class-font-awesome-icons-css.php
Closes #998.
Some unnecessary code was left after changing the formula for icon dimensions.
----
1. Add FA Blocks with Temeisle Icons and FA Icons
2. Set the same size and padding.
3. They should look the same.
----
> Remove padding from frontend for FA Block

- inc/css/blocks/class-progress-bar-css.php
- src/blocks/blocks/progress-bar/block.json
- src/blocks/blocks/progress-bar/edit.js
- src/blocks/blocks/progress-bar/inspector.js
- src/blocks/blocks/progress-bar/style.scss
- src/blocks/blocks/progress-bar/types.d.ts
- src/blocks/blocks/section/editor.scss
Closes #818.
- Add font-size for Title and Value on Outer style
- Tooltip will inherit the progress bar as the background color
----
----
> Progress Bar enhancement

- src/css/editor.js
Fix: https://github.com/Codeinwp/otter-blocks/issues/1155
Closes #.
----
----
> Fixing overriding & preventing same errors from appearing again

- inc/css/blocks/class-form-css.php
- src/blocks/blocks/form/block.json
- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/form/style.scss
- src/blocks/blocks/form/type.d.ts
> In the future, we will have a Form React Developer position. - Robert
Closes #1121.
- Add Input Background Color.
- Fix extra space.
- Change defaults for gaps.
- Fix font size units.
- Fix the required color.
Row style messages:
Background for inputs
----
1. Insert a form
2. Ensure that the styling options are working correctly 
----
> Form enhancement

- inc/class-blocks-animation.php
- inc/plugins/class-dashboard.php
- inc/server/class-dashboard-server.php
- src/animation/editor.scss
- src/animation/frontend.js
- src/animation/index.js
Closes #1060
⚠️ If you reuse a WP instance with another version of the plugin. After replacing the build. Go to Settings > Otter and press Regenerate.
Hide animations until the JS handler is loaded. This is a minor enhancement for slow internet connections.
Regenerate style now will delete the transient for optimized CSS.
----
1. Add any block.
2. Put some animation.
3. Preview and be sure to use ⚠️ slow 3G to see if the animation is hidden.
----
> Hide animations until fully load

- src/blocks/blocks/flip/style.scss
Closes #1179 .
Fix a bug that did not make the `backface-visibility` work without extra props.
----
1. Use Firefox
2. Add a Flip with content on both faces
3. The back face should be visible from the front and vice versa
----
> Fix Flip block back face visibility for Firefox

- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/blocks/button-group/group/edit.js
- src/blocks/helpers/google-fonts.js
Closes #.
Make the google fonts work on Mobile/Tablet in Post/Page.
----
1. Make a Page/Post
2. Insert Adv Heading and select a Google Font
3. Switch to Mobile/Tablet
----
> Fix Google Fonts for view change n Post/Page

- inc/plugins/class-dynamic-content.php
- src/animation/index.js
- src/blocks/plugins/conditions/index.js
- src/blocks/plugins/dynamic-content/link/fields.js
- src/blocks/plugins/dynamic-content/link/index.js
- src/blocks/plugins/galley-extension/index.js
- src/blocks/plugins/image-extension/index.js
- src/blocks/plugins/masonry-extension-old/index.js
- src/blocks/plugins/masonry-extension/index.js
- src/blocks/plugins/menu-icons/index.js
- src/blocks/plugins/sticky/index.js
- src/css/index.js
- src/pro/plugins/wc-integration/index.js
Closes #1199.
This Dynamic Link format doesn't work for few blocks like:
- Buttons
- Advanced Buttons
- Icon
Now we have a different control for that. Her's a picture:
----
----
> Dynamic Link for Buttons

- src/blocks/blocks/countdown/inspector.js
- src/pro/blocks/countdown/index.tsx
- src/pro/blocks/index.js
Closes #.
Pro Features:
- Timer Mode
- Interval Mode
- End Action tab
----
Make sure the mentioned features are locked for Non-Pro users. 
```javascript
new QueryQA().select('blocks').where({ has: { blocks: ['countdown'] }}).run()
```
You can use the Query Engine since it has some countdown with pro features activated. You can test it to see if they are breaking when used in Non-Pro.
----
> Add Countdown new features to Pro

- src/blocks/blocks/review/style.scss
- src/blocks/components/sync-color-panel/index.tsx
- src/blocks/helpers/helper-functions.js
Closes #1221.
It should address Review Block padding not working for Pros/Cons when used with one column layout.
----
> Fix Review Padding issue. closes #1221

- inc/css/blocks/class-advanced-column-css.php
- inc/css/blocks/class-advanced-columns-css.php
- src/blocks/blocks/font-awesome-icons/style.scss
- src/blocks/blocks/icon-list/editor.scss
- src/blocks/blocks/icon-list/style.scss
- src/blocks/blocks/section/column/block.json
- src/blocks/blocks/section/columns/block.json
Closes https://github.com/Codeinwp/otter-blocks/issues/1210.
Fixes inheritance of Borders in Section & Icon Block, as well as ThemeIsle icon color.
----
> Fix Border & Icon Color Inheritance

- docs/blocks/editor.md
- docs/blocks/first-block.md
- docs/blocks/style-with-php.md
- src/blocks/frontend/sticky/index.ts
- src/pro/plugins/sticky/index.js
Closes #.
- When a sticky element is active, add a global class name to the `body`.
- Add closing via class or anchor (PRO feature)
----
1. Make a Section/Column/Group a Sticky.
2. Add a Button inside, then add a link to `#o-sticky-close`
3. Set the sticky to FLOAT MODE.
4. Preview the page; when you press the button, the sticky should disappear.
----
> Add closing to Sticky in Float Mode

- inc/css/class-css-utility.php
Closes #713.
When you initialize, you can now optionally define a shorthand for the media queries:
```
$default_queries = array(
'desktop' => '@media ( min-width: 960px )',
'mobile'  => '@media ( max-width: 960px )'
);
$css = new CSS_Utility( $block, $default_queries );
```
And in your properties, you can also define the media:
```
array(
'property' => '--o-posts-title-text-size',
'value'    => 'customTitleFontSizeMobile',
'unit'     => 'px',
'media'    => 'mobile' // or even '@media ( max-width: 960px )'
),
```
And always, to keep things separated, you can also use the old way of defining queries. Or you also use the shorthand in the main query property:
```
$css->add_item(
array(
'query'      => 'desktop',
'properties' => array(....)
....
)
);
```
When you test this Irinel, can you make …
> CSS Utility Improvements

- src/blocks/frontend/lottie/index.js
Closes #1273.
Fix reverse mode for Click and Hover
----
----
> Fix lottie reverse mode

- src/blocks/blocks/sharing-icons/style.scss
Closes #1274 .
Sharing alignment now uses the entire width of the container
----
1. Add two paragraphs and a sharing icons block between them.
2. Change the alignment for sharing icons.
----
> Fix sharing alignment

- inc/plugins/class-dynamic-content.php
Closes https://github.com/Codeinwp/otter-internals/issues/19.
This allows users to use magic tags to display Dynamic Values in places where they can't simply use the formats. The format of the dynamic tags will be something like this:
Tag Structure: {otterDynamic?type=postTitle&context=widgets}
All the possible options are same as Dynamic Value.
Global Parameters
- type: Dynamic Value type to show. Possible values are:
- before: The text to prepend the dynamic value.
- after: The text to append the dynamic value.
- context: The ID of the post. If not used the current post will be used. It can be widgets for widgets screen and query if used inside the query block
- default: The default value to return.
Here are all the available types and possible values that can be used with them.
Free:
- …
> Add Magic Tags

- inc/css/blocks/class-flip-css.php
- src/blocks/blocks/flip/block.json
- src/blocks/blocks/flip/edit.tsx
- src/blocks/blocks/flip/editor.scss
- src/blocks/blocks/flip/inspector.js
- src/blocks/blocks/flip/style.scss
- src/blocks/blocks/progress-bar/types.d.ts
- src/blocks/plugins/copy-paste/adaptors.ts
Closes #1323
Updating the adaptors based on the recent enhancements.
Fixing Flip Block attributes type and Editor behaviour.
----
Affected block: Progress Bar and Flip
----
> Fix Copy/Paste old definitions & Flip fix 

- inc/class-blocks-css.php
- src/css/index.js
- src/css/inject-css.js
This fixes the issue with Custom CSS extension not working with FSE & Tablet/Mobile view in Post Editor.
----
Make sure it works correctly both in back/front in both FSE/Post Editor. It won't work on Widgets/Customizer.
----
> Make Custom CSS work with FSE

- inc/css/blocks/class-advanced-column-css.php
- inc/css/blocks/class-advanced-columns-css.php
- inc/css/blocks/class-shared-css.php
- src/blocks/blocks/advanced-heading/inspector.js
- src/blocks/blocks/advanced-heading/style.scss
- src/blocks/blocks/section/column/edit.js
- src/blocks/blocks/section/columns/edit.js
- src/blocks/blocks/section/editor.scss
- src/blocks/blocks/section/style.scss
Closes #1328.
This should fix the issue introduced by the last version, where Buttons were inheriting the color of links too.
----
Instructions on how to reproduce and test: https://github.com/Codeinwp/otter-blocks/issues/1328
----
> Fix Button Color issue in Section

- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/index.js
- src/blocks/blocks/form/nonce/block.json
Closes #1340.
Fix missing data:
- nonce
- form option
----
1. Add Form in FSE Template
2. Check if it works
----
> Fix missing information from Form in FSE

- inc/class-registration.php
- inc/plugins/class-dynamic-content.php
- src/blocks/plugins/dynamic-content/media/media-content.js
Closes #1272 .
This should fix https://github.com/Codeinwp/otter-blocks/issues/1272 as well as the issue with Dynamic Images not working correctly without Pretty Permalinks.
----
> Query loops with Otter Dynamic Values and Images

- inc/render/class-review-block.php
- src/blocks/blocks/review/edit.js
Closes #1375.
This makes sure whatever the rating is, the minimum value stays at 1.
----
- Please make sure the rating numbers, both in front/back, are same and consistent regardless of the weight scale used, 1-10 or 1-5, which can be toggled from Otter settings
----
> Make sure Review Ratings are minimum 1 for Schema

- src/blocks/frontend/countdown/index.ts
Closes #1377 .
Add a fix for Evergreen reset and docs.
----
1. Add a Countdown with the mode Evergreen
2. Set the time, then preview.
3. Test time reset on __refresh__, which has the conditions:
1. Time is over.
2. Timezone has changed 
3. Deadline has changed.
If you think the time should have reset in a situation that is not mentioned, please post the scenario 🙏 .
For Timezone, you can use the Sensor tab from the browser Dev Tools (Chrome)
----
> Evergreen Reset Fix

- src/blocks/blocks/button-group/button/block.json
Closes #1106.
Fixes the issue with Button Group block styles not loading properly in front in FSE.
- Use the default theme in WP 6.0.3 and use the FSE editor to add a Button Group, while no Button Block is present, and the Button Group styles don't look normal.
- With this PR, the issue should be solved.
----
> Fix Button not loading properly in some FSE versions

- inc/class-registration.php
- inc/server/class-form-server.php
- src/blocks/frontend/form/captcha.js
Closes #1053.
This allows Otter Blocks' Form block to replace reCaptcha with hCaptcha API using hCaptcha's WP plugin. Changes required on hCaptcha can be found here: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/208
----
You can install Otter and configure hCaptcha plugin from here: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/pull/208
----
> Add hCaptcha Integration

- inc/render/class-review-block.php
- src/blocks/blocks/review/block.json
- src/blocks/blocks/review/edit.js
- src/blocks/blocks/review/inspector.js
- src/blocks/blocks/review/style.scss
- src/blocks/blocks/review/type.d.ts
- src/pro/plugins/wc-integration/index.js
Closes #1397.
This will add a new Image Size option to allow users to select which image size to load, defaults to Medium.
----
- Test it with Review Block normally as well as with it being synced to Woo and make sure there are no console errors.
----
> Add Image Size option to Review Block

- src/blocks/plugins/options/editor.scss
- src/blocks/plugins/options/global-defaults/block-item.js
- src/blocks/plugins/options/global-defaults/index.js
- src/blocks/plugins/options/index.js
Part of #1355.
https://www.loom.com/share/0c913e71e8f74f88b4a30a0b884c6b8b
Part of the Global Defaults UI reworks and changes it from the Popup UI to the new Navigator components introduced in WordPress 5.9.
Feedback appreciated @mghenciu @JohnPixle 
----
- Try to make sure everything works as previously from 5.9 to 6.1
----
> New Global Defaults UI

- src/blocks/frontend/form/captcha.js
- src/blocks/frontend/form/index.js
Closes #1424.
Fix the checking condition when verifying the existence of captcha tokens.
----
----
> Fix Form in Popup Block

- plugins/otter-pro/inc/plugins/class-block-conditions.php
Closes #1401.
This PR improves how we detect and handle query in Block Conditions' Query String option.
----
I'll be good to try this out with various different combinations to see if it works well or if it gives any errors. Here are few types of things that can be used
1. Just using this to match anything that has utm_source in the URL string or even if it's only utm_source like example.com?utm_source or example.com?utm_source=facebook
`utm_source`
2. Similarly using multiple query strings.
```
utm_source=facebook
utm_campaign=discount
```
3. Another is to use array instead of a single value, like example.com?utm_source[]=facebook&utm_source[]=twitter
```
utm_source[]=facebook
utm_source[]=twitter
```
And various different combinations to make sure it works fine and you don't see any …
> Query String improvements

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/block.json
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/components/sortable.js
- src/blocks/blocks/posts/types.d.ts
Closes #1432.
Adds option to display last modified date in Posts Block. Skipping QA as it's a simple edit that works without an issue.
----
----
> Add last updated date option to Posts block

- src/blocks/helpers/icons.js
Closes #.
Changes `fill-rule` to `fillRule` and `clip-rule` to `clipRule` to fix the console warnings.
----
When an otter block icon is rendered, there should not be any warning in the console.
----
> Fix: icons rules

- src/blocks/helpers/helper-functions.js
Closes #1468 .
Add an extra check condition.
----
See issue.
----
> fix: add null check condiftion when trying to get a CSS var value

- inc/integrations/providers/class-mailchimp.php
Closes #1489 .
Increase the limit of the contact list requested.
----
ℹ️ You need Mailchimp Pro to have more than 1 list of contacts. A license is required.
----
> fix: increase the number of contact list (mailcimp)

- inc/integrations/api/form-response-data.php
- inc/render/class-form-nonce-block.php
- inc/server/class-form-server.php
- src/blocks/blocks/form/style.scss
- src/blocks/frontend/form/index.js
Closes #1465
Add two mechanisms for spam protection:
- Interaction time: the user needs to spend at least 5 seconds on the page since it's loading.
- Honey Bot for bots. The protection block now generates an additional checkbox. Since it is invisible, only scripted bots can access it. If the value of the checkbox is "true", then we reject the request.
----
See if you can trigger the bot detection. 
----
> Add Built-in Spam protection for Form Block

- inc/class-pro.php
- inc/class-registration.php
- plugins/otter-pro/inc/plugins/class-patterns.php
- src/blocks/global.d.ts
- src/blocks/plugins/upsell-block/index.js
Closes #1511.
Replace the link form the patterns upsell from
`themeisle.com/plugins/otter-blocks/upgrade/` to `themeisle.com/plugins/otter-blocks/patterns/`
----
> Replace the link from patterns upsell

- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/helpers/block-utility.js
Closes #1510 .
The duplicated block was deleting the id of the original block from Global Id pool. Now when an ID is changed is case of duplication, it will not longer delete its original ID via cleaning function.
ℹ️ Console log will be removed after QA.
----
1. Make a block
2. Duplicate it
3. Check the console. The console should show the fallowing information:
4. Preview the page
ℹ️ If you encounter the error, please 🙏  post a screenshot with the Console or a test instance.
----
> Fix Block id duplication on Duplicated Block action

- inc/render/class-review-block.php
Closes #1491.
Since `get_json_ld()` is hooked in the footer, it can sometimes get the wrong current post.
Passes the post ID to the function to get the author based on it.
Hardeep found that in the user's case there must be a footer widget that uses `setup_postdata`, so he tested it and this fixes the issue. So, we only need a general testing of this and to make sure it works in places outside of Posts context, like widgets and FSE.
----
> Wrong author in review block schema

- src/css/editor.js
Closes #1507.
- When trying to delete the `ticss` class with backspace from the `Additional Classes`, the input is filled with `ticss` strings (see [here](https://www.loom.com/share/0bbaa6e047f44042811384bc7429e755)).
- This PR lets the user delete the class (meaning that the `Custom CSS` is no longer applied) until the `Custom CSS` is modified, which causes the `ticss` class to be added again.
- Also, made some changes to limit the re-renders of the component. They should not influence the behavior.
----
- Add Custom CSS to a block.
- From the Advance tab, try to remove the CSS class by pressing backspace.
- Modify the Custom CSS and the class should be added again.
- Make sure that besides this, everything else behaves the same.
----
> Fix: Additional classes behavior when deleting ticss class

- inc/plugins/class-dynamic-content.php
Closes #1508 .
Applies `the_content` filter on the dynamic value for post content.
----
- Using a FSE theme, add a dynamic value with `Post content` for a post in the Homepage, as seen below:
- Add some blocks on the specific post and they should look as expected in the frontent:
----
> CSS not rendering on dynamic value for post content

- src/css/editor.js
Closes #1544.
- If the custom CSS is empty there should be no `ticss` class.
- Fixes the last comment from https://wordpress.org/support/topic/problem-with-removing-unnecessary-classes/#post-16532550
----
- Add custom CSS to a block and there should be the additional class `ticss-...`
- If the CSS gets removed that class should disappear.
- If there are other additional classes to that block, they should not be affected.
----
> fix: remove ticss class if custom CSS is empty

- src/dashboard/style.scss
Closes #1541 .
Before
After
----
1. Go to Otter Dashboard.
2. Close the tabs like in the above picture.
----
> Remove redundant border on closed tabs in Dashboard

- inc/class-base-css.php
- inc/class-blocks-css.php
- src/css/inject-css.js
Closes #1542.
- In the context of the issue (FSE theme, home page), the `$post` will be the first post from the query, not the actual page, so the correct blocks were not considered. 
- This PR adds an additional check to select the correct blocks and add their custom CSS.
----
- Use only the blocks-css plugin
- Add custom CSS on a block from a home page using an FSE theme
- The custom CSS should load just the same as in usual contexts.
----
> Fix blocks-css with FSE themes

- src/blocks/plugins/dynamic-content/editor.scss
- src/blocks/plugins/dynamic-content/value/fields.js
Closes #1504 .
Adds a small preview for the Dynamic Value in the popup.
----
- Add a dynamic value
- After selecting the type of the value, a preview should appear below
----
> Feat: Add preview for dynamic value

- src/blocks/blocks/popup/edit.js
- src/blocks/blocks/popup/index.js
- src/blocks/blocks/popup/style.scss
- src/blocks/helpers/icons.js
Closes #1495.
Add two popups variations for free users:
- Popup with Image and Text
- Popup with Form
[Updated]
----
1. Insert a Popup.
2. Test each variation.
----
> Add Popup Variations

- inc/class-registration.php
- inc/css/class-block-frontend.php
Closes #1436 .
Tweak the hooks that generate the dynamic CSS.
Setup
Without fix
With fix
----
1. Make a Custom Neve Layout with Otter Blocks and add the option Global (so it can show up in any page)
2. Check the pages and see if the CSS is working.
3. Since this is a tweak in pipeline, it is recommended to check Widgets and FSE for regressions.
----
> Fix Neve Custom Layout CSS

- inc/render/class-stripe-checkout-block.php
Closes #1564 .
It seems that error handling was missing from Stripe Checkout Render when requesting product info and price.
Added a simple error handling that displays a message on the page.
When something wrong happens, this message will appear.
If the product is no longer valid to purchase: archived or deleted. 
--- 
The following explanation should be added in docs regarding the errors:
For errors `'An error occurred! Could not retrieve product information!'` and `'An error occurred! Could not retrieve product information!'`, you have the following causes:
- The Stripe API Key is no longer valid.
- Stripe Servies are no longer working. [Link](https://status.stripe.com) for users to check.
- The Stripe API is from a different account. Every product has its own id based on account. You …
> Fix Stripe Checkout Button when switching accounts

- inc/class-main.php
Closes #1594 .
Our filter will load the mime types & metadata only if no other filter adds them.
ℹ️ Tested with SVG Support, and we do not accidentally override the data generated 👍 
Before: Load SVG has no details about the size. When trying to edit, the window shows empty. When using in Customizer for Website Logo, the Skip crop button does not exist, and Select & Crop does not give any feedback.
https://user-images.githubusercontent.com/17597852/230579406-3eb65a07-e036-4a1b-81d0-baf3cc20d599.mp4
After: SVG has details about the size, the edit window is no longer empty, and you can see the dimensions in the right corner. On Customizer, all buttons are working. 
https://user-images.githubusercontent.com/17597852/230579658-4adfd890-d56a-4a07-b857-851113e5f7e9.mp4
----
1. Load an SVG. You …
> Fix SVG crop in Neve

- src/blocks/frontend/accordion/index.js
Closes #1617 .
The `hasSchema` data attribute is `false` when the FAQ Schema is disabled, but the check only checked if it existed. So, it was added anyway.
- Add an Accordion block
- Set the FAQ Schema to true and the schema should be added in the frontend
- Set the FAQ Schema to false and the schema should be removed.
----
> Fix: accordion schema

- src/blocks/blocks/section/components/separators/editor.scss
- src/blocks/blocks/section/components/separators/style.scss
Closes #1597.
Make the top and bottom dividers on top of common things more consistent with Z positioning.
----
1. Add a Section block.
2. Add some content and dividers (you can find them in the Style tab).
3. The dividers must be on the top of the content, with exceptions*
⚠️ *Some blocks are built to be on top of others, like Maps (image below) or Sticky blocks. Dividers act like decorators and not blockers. For those kinds of Blocks, there will be no issue if they are blocked or not. It is up to he user to use them correctly. 
----
> Make Z index consistent for Section Dividers

- inc/class-main.php
- otter-blocks.php
- plugins/otter-pro/otter-pro.php
Register Otter Free & Pro to SDK for compatibility check
Closes #1460.
Add filters for registering Otter Free & Pro to Themeisle SDK for compatibility.
----
1. Install an editing file plugin like [WPIDE](https://wordpress.org/plugins/wpide/) in your instance.
2. Install both Otter Free & Pro
3. Edit the version (something lower than 2.0) in `otter-blocks.php` in the Otter Blocks folder.
4. Check if you see a notice in Dashboard.
5. Redo the step 3 & 4 for Otter Pro in  `otter-pro.php`
You can also download the older Otter Free version from [here](https://wordpress.org/plugins/otter-blocks/advanced/) and check if the Otter Pro shows a notice for upgrading.
Video
https://user-images.githubusercontent.com/17597852/228480275-4460f30d-a543-4376-966c-99c094f3b719.mp4
----
> Add Otter Free & Pro compatibility to SDK

- src/blocks/blocks/form/common.tsx
- src/blocks/blocks/form/editor.scss
- src/blocks/blocks/form/input/inspector.js
- src/blocks/blocks/form/style.scss
- src/blocks/blocks/form/textarea/inspector.js
Closes #1513.
The form fields are not more fluid with the new Width setting. Some real CSS magic was used to achieve this.
https://user-images.githubusercontent.com/17597852/230620136-383133a8-c9a7-4e1d-97fd-fc1b62afa9aa.mp4
----
Play with the Width options of the Form fields like in the video above.
ℹ️ This is for Desktop and Tablets. On Mobile should look linear like the SS from above.
Things to look out for:
- Ensure the current Forms dimensions from the page stay consistent with the new update.
- No styling options from Form break.
By default, every block with Form as the direct parent will have `width: 100%` and `margin: 0px`. Some Blocks can change those options ( like Image ). They can act like a column block and integrate into the flow by changing the options. 
ℹ️ Is the user's …
> Make Form field more fluid

- inc/css/blocks/class-shared-css.php
- src/blocks/blocks/accordion/editor.scss
- src/blocks/blocks/accordion/group/edit.js
- src/blocks/blocks/accordion/style.scss
- src/blocks/blocks/flip/edit.tsx
- src/blocks/blocks/flip/editor.scss
- src/blocks/blocks/flip/style.scss
- src/blocks/blocks/section/column/edit.js
- src/blocks/blocks/section/columns/edit.js
- src/blocks/blocks/section/editor.scss
- src/blocks/blocks/section/style.scss
- src/blocks/helpers/blocks.d.ts
- src/blocks/helpers/helper-functions.js
- src/blocks/helpers/utility-hooks.js
Closes #1595.
- Besides the `has-dark-bg`, this PR adds also `has-light-bg` to make it work in nested blocks (i.e. accordion inside a column). This shoud fix the bug described in the issue.
Other fixes:
- The automatic text color didn't work properly for the Flip Card because the CSS from the `has-dark-front-bg` and `has-dark-back-bg` was applied to the whole flip block, not the specific parts (front/back).
- For the Accordion Block, as in Flip Card, the `has-dark-active-title-bg` was applied to all titles, not just active ones.
- When using Neve, the `has-dark-bg` had no effect on paragraphs in the editor because Neve's selector was more specific, so this PR adds a more specific selector to avoid this.
The affected blocks are Flip Card, Section Block, Column Block, and Accordion.
- Add …
> Fix: automatic detection of background darkness

- src/blocks/plugins/dynamic-content/value/fields.js
Closes #1652.
As described in the issue, the dynamic value preview doesn't work in widgets, such as sidebar. 
This PR makes the preview appear only in the editor, since it doesn't make much sense in the widgets (for example 'Post Title' cannot be previewed because the post that will contain that widget is unknown in that moment)
- Go to Appearance -> Widgets
- Add a dynamic value
- It should not throw any error in the console and the preview will not appear.
----
> Fix: dynamic value preview breaking the block

- inc/class-base-css.php
- inc/class-registration.php
Closes #1656 .
Since we were getting the content from all the widgets, some inactive widgets were activating our deps without being on the page.
When you delete a block from a widget, the widget goes to Inactive widgets and they are not displayed on the page. Our dependency verification did not count for this case and thus the problem. 
Many thanks to @preda-bogdan for helping out.
https://github.com/Codeinwp/otter-blocks/assets/17597852/07e2ce7e-bbd1-4d1d-8e09-505c7a6a855f
----
Follow the instruction from the issue to reproduce the error. After applying the fix, there should be no extra dependencies loaded on the page, like in the video above.
Note from Hardeep: It will be interesting to test it with various widgets and see to confirm it works properly all the time.
----
> Do not enqueue dependancy for inactive widgets

- src/blocks/plugins/welcome-guide/index.js
Closes #1637 .
Change Modal text for Pro Users.
All the messages can be found here:
https://github.com/Codeinwp/otter-blocks/blob/46b082a860847814dcc4985b520d4eb896a86f50/src/blocks/plugins/welcome-guide/index.js#L113-L188
https://github.com/Codeinwp/otter-blocks/assets/17597852/3fff9ac0-844e-4f39-89c9-e9657db903bb
----
Check if the modal is working correctly and if the text change does not produce an error.
----
> Improve text in Onboarding Modal for Otter Pro 

- inc/render/class-stripe-checkout-block.php
- src/blocks/blocks/stripe-checkout/inspector.js
Closes #1563.
Add rich text editor for Stripe Checkout messages. This will alow the usage of images and links.
ℹ️ A Modal was used (same as Autoresponder) since it offers more space which prevents some weird glitches (mostly related to Add Link pop-up)
https://user-images.githubusercontent.com/17597852/234594934-c9e908d0-7a3f-4803-a425-a564feddde67.mp4
----
⚠️ Make sure to have a Stripe account (Testing Mode) and some products.
1. Insert a Stripe Checkout
2. Edit the messages like in the video
3. Make sure that they are displayed.
----
> Add Rich Text Editor for Stripe Checkout block

- src/blocks/frontend/accordion/index.js
Closes #1579.
This was a very ubiquitous bug in a very edge-case situation.
FQA generation works fine, but for some unknown reason, using the situation described in the issue, a very strange situation happens with the query that extracts the accordion title:
```javascript
const question = item.querySelectorAll( '.wp-block-themeisle-blocks-accordion-item__title' )[0].innerText;
```
This query return `''` even if the element it selects has the value for.
As a solution, I changed the query to a more simple one that extracts the data directly from the title tag using `innerHTML` instead of `innerText` from the title container:
```javascript
const question = item.querySelector( ':scope > .wp-block-themeisle-blocks-accordion-item__title > *' ).innerHTML;
```
ℹ️ Regarding the use of the Neve …
> Fix Accordion FQA data extraction

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr-checklist.yml
Closes #1666.
- Adds the PR checklist workflow from Neve.
- All checks from the PR description body should be checked for the workflow to show as passed.
- It can be skipped  with the `pr-checklist-skip`.
----
> Add PR checklist workflow

- inc/plugins/class-dynamic-content.php
Closes #1600.
Sanitize the page's content when using Dynamic Content by removing references to dynamic content tags.
https://user-images.githubusercontent.com/17597852/231764637-c975ebbb-ba15-4f3a-b23a-df3b094d065c.mp4
----
1. Make a custom layout like it is mentioned in the issue.
2. When adding Dynamic Content, no error should appear in Editor.
----
> Fix infinite loop in Dynamic Content for Neve Custom Layout

- inc/integrations/class-form-settings-data.php
- plugins/otter-pro/inc/plugins/class-form-emails-storing.php
- src/pro/plugins/form/index.js
Closes #1676, https://github.com/Codeinwp/otter-internals/issues/88.
- Change the column name from `Email` to `Title`
- Change the default option save location to `database & email` for pro users.
- Use a generic name for the `otter_form_record` post: `Submission #<post_id>`
- Set `show_in_rest` to `false` for otter_form_record
- When activating Otter pro, the default option for `Save Location` should be `Database and Email`.
- The saved submissions should be named `Submission #<post_id>` and the emails should be visible only in the post meta, visible when editing the submission data.
----
> Fix: use a generic name for the title & change default storing location

- inc/server/class-form-server.php
Closes #1677 .
If you have the option to save set as `database-email` and the Email service is not working, the error from email not sent will be considered as a warning and thus will be non-blocking.
ℹ️ I was considering notifying the admin via email about this problem then I realized that I could not send the email if the Email service is not working 🤦 
----
Make an instance where Email SMTP is not set-up. Set the options to save the data as `Database & Email` in a Form. Fill the form and submit then check if it was saved in the Submissions.  
----
> Add email failover for Form Block

- plugins/otter-pro/inc/class-main.php
Closes #1703.
We moved the Otter menu page to the top level and the Pro handler was not updated.
----
Same as in the [issue](https://github.com/Codeinwp/otter-blocks/issues/1703#issue-1747638463):link:.
----
> Fix wrong otter page menu hook fix

- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/inspector.js
Closes #1702.
- Fixed the condition for checking the values.
- Now the Options will not show during the loading.
- Fixed a wrong field name (very subtle bug -- introduced in https://github.com/Codeinwp/otter-blocks/commit/320052caecb5218b8378f77e3d6efd65139b1885 ): `fromEmail` instead of `fromName`
https://github.com/Codeinwp/otter-blocks/assets/17597852/f8345e99-e226-4157-816f-cabb2e2dea8b
----
Check the toggle for the first four options like it is described in the issue.
ℹ️ If you enable one of the top four fields and do not make any changes when you refresh the page, you will not see them enabled -- this is the default behavior. Unchanged fields should not be shown. 
----
> Fix Form options toggle

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/components/layout/featured.js
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/edit.js
- src/blocks/blocks/posts/inspector.js
Closes #1572.
The categories list used only `category` taxonomy. Now it will detect based on the `postType` slug.
E.g.: `product` post type will have `product_cat` as the taxonomy slug.
https://github.com/Codeinwp/otter-blocks/assets/17597852/0aae6972-4dea-4f1a-a67c-2fbad0a482f7
----
1. Add WooComerce and import the samples 
2. Make a new post page and add a Posts Block
3. In the Settings > Categories check if you have category related to Woo.
ℹ️ When loading the Product for the first time, you see a loading status then `No Posts` for a short period, and a loading status again like in the video. This is caused by the way the loading is done.
ℹ️ When switching between post types, the categories will be marked as `Invalid` if they are not found. When clicking on it should remove them -- …
> Improve taxonomy detection for Posts Block

- development.php
- inc/class-pro.php
- inc/class-registration.php
- inc/plugins/class-dashboard.php
- otter-blocks.php
- plugins/otter-pro/otter-pro.php
Closes #1712.
The Otter page is now in the Admin panel and not Options.
----
1. Check the instruction from the issue.
2. Create a new Post and open the Console (F12 - on some browsers) then run this command: `window.location = themeisleGutenberg.optionsPath` -- this command should take you to the Otter menu page.
----
> fix: replace otter page path to admin

- inc/integrations/api/form-response-data.php
- inc/integrations/class-form-settings-data.php
- inc/server/class-form-server.php
- src/blocks/frontend/form/index.js
- src/blocks/test/e2e/blocks/form.spec.js
Closes #1706.
The redirect link needed to be added to the response.
----
1. Make a Form and a redirect link. Save and bullish the post.
2. View the page and after completing the form with success, you should be redirected.
----
> Fix missing redirect link on response

- plugins/otter-pro/inc/plugins/class-dynamic-content.php
- src/pro/plugins/dynamic-content/value-edit.js
Closes https://github.com/Codeinwp/otter-internals/issues/83
Added support for the following types:
'button_group',
'checkbox',
'color_picker',
'data_time_picker',
'date_picker',
'radio',
'range',
'select',
'time_picker',
'true_false',
----
🧪 Here are some ACF fields example. You can import them by going to the Tools tab in ACF menu.
[acf-export-2023-05-25.json.zip](https://github.com/Codeinwp/otter-blocks/files/11566554/acf-export-2023-05-25.json.zip)
Things to test:
- Dynamic to do break. We do not want any side effects.
- New ACF options do not break the page.
ℹ️ For most fields, we display the value ACF gives: email, URL, time, etc. But some areas are of type array like the Choice section, and they have the same option to display: value, label, or both. In the case of `both` options, …
> Add support for more ACF fields in Dynamic Content

- src/dashboard/components/pages/Integrations.js
Closes #1722 .
Add missing stripe info.
----
Go to Admin > Otter Blocks > Integrations > Stripe and click `More Info`.  It should open a docs page.
----
> Add missing stripe info link

- src/blocks/plugins/image-extension/edit.js
Closes #1720 .
Fix the Box Shadow image extension in Editor for Core Image.
----
1. Create a core Image Block
2. In Inspector, activate the shadow in Box Shadow tab.
3. You should see the shadow in Editor.
----
> Fix image box shadow

- inc/integrations/api/form-response-data.php
- inc/integrations/class-form-settings-data.php
- inc/plugins/class-options-settings.php
- inc/render/class-form-multiple-choice.php
- plugins/otter-pro/inc/plugins/class-form-pro-features.php
- plugins/otter-pro/inc/render/class-form-file-block.php
- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/file/inspector.js
- src/blocks/blocks/form/input/inspector.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/form/multiple-choice/inspector.js
- src/blocks/blocks/form/textarea/inspector.js
- src/blocks/blocks/form/type.d.ts
- src/blocks/editor.scss
- src/blocks/frontend/form/index.js
- src/blocks/helpers/use-settings.js
- src/pro/blocks/file/inspector.js
- src/pro/components/webhook-editor/index.tsx
- src/pro/plugins/form/index.js
Closes #.
Add Webhook triggers to Form.
----
The idea of the webhook is that after a form has been submitted, it will ping a given URL which will trigger an external action/workflow (e.g.: send an SMS, email, a Slack message).
In this feature, we will support Zappier and IFTTT. The way they function is the same regarding the API call. (which means we do not need separate codes for them).
For the features to work, we need three parts:
- the URL of the webhook
- the method: GET, POST,  PATCH
- the headers.
Those settings will be managed in the Webhook editor available in Form at Form Options > Webhook (check screenshots from above).
When a user submits a form, the data of the form will be prepared in a payload with the structure (in JSON format): `key: value`. The `value` will be the field …
> Add Webhook to Form

- .distignore
- plugins/blocks-animation/readme.md
- plugins/blocks-animation/readme.txt
- plugins/blocks-css/readme.md
- plugins/blocks-css/readme.txt
- plugins/blocks-export-import/readme.md
- plugins/blocks-export-import/readme.txt
- readme.md
This updates WordPress compatibility version as updating through readme.txt wasn't possible due to changes made to readme.md.
> WP Version Bump

- src/blocks/blocks/section/components/separators/editor.scss
- src/blocks/blocks/section/components/separators/style.scss
- src/blocks/blocks/section/editor.scss
- src/blocks/blocks/section/style.scss
Closes #1751.
Adjust section dividers so they can be behind the content but in front of the background.
----
1. Make a section block with content.
2. Insert the dividers.
3. Ensure the dividers are behind the content but in front of the Section background.
----
> Adjust z-index for section dividers

- src/blocks/blocks/accordion/group/inspector.js
- src/blocks/blocks/advanced-heading/inspector.js
- src/blocks/blocks/button-group/button/inspector.js
- src/blocks/blocks/button-group/group/inspector.js
- src/blocks/blocks/countdown/inspector.js
- src/blocks/blocks/flip/inspector.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/google-map/inspector.js
- src/blocks/blocks/icon-list/inspector.js
- src/blocks/blocks/popup/inspector.js
- src/blocks/blocks/posts/inspector.js
- src/blocks/blocks/review/inspector.js
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/inspector.js
- src/blocks/blocks/slider/inspector.js
- src/blocks/blocks/tabs/group/inspector.js
- src/blocks/helpers/block-utility.js
- src/blocks/index.js
- src/blocks/test/e2e/blocks/global-memory.spec.js
Closes #1752 .
I implemented a Global State Memory that keeps the data when the content editor is transformed to an `iFrame` during the Preview from Desktop to Tablet/Mobile.
In the root window, we save global values that keep the state in a dictionary structure. Since the root window data is `readonly` when accessed by the `iFrame`, we need to use the browser event system to transmit the change from the `iFrame` via `postMessage`. 
ℹ️ Even if Gutenberg now has tabs for the Inspector. The Core Block has no mechanism for retention of state. Like Otter, they reset on the viewport change. Until they implement such a feature, we will use our solution.
https://github.com/Codeinwp/otter-blocks/assets/17597852/cb196357-347e-4efe-bad0-6902041293ae
----
When changing the viewport, the state of the …
> Fix inspector header reset on transition between Desktop to Tablet/Mobile

- inc/plugins/class-dashboard.php
Closes #1810 
Add CSS to hide the "Add New" button. This way it will prevent the user from accidentally creating a submission.
----
- Install Otter Pro on a WordPress multisite installation.
- Create multiple sites and visit one of them while being logged in using the super admin user of the network
- Visit Otter Blocks > Form Submissions -> There is should NO "Add New" button.
----
> Hide "Add New" btn in Submission Dashboard 

- src/blocks/blocks/progress-bar/style.scss
Closes #1776 
The Progress Bar can be tiny but not too big on Mobile.
For Mobile (viewport with less than 600px width), the `height` will be between `0px and 64px` instead of the fixed `30px`.
----
1. Create a Progress Bar.
2. Add some colossal height.
3. On the Desktop should be the same size but on the Mobile should be smaller.
4. Now make a smaller Progress Bar (height less than 64px).
5. It should look the same on both Desktop and Mobile
ℹ️ Progress Bar does not have responsive options; thus, the constrain is implemented.
----
> Add height & font-size scaling for Progress Bar

- src/blocks/blocks/stripe-checkout/edit.tsx
Closes #1815
Added `?.` as a guard against undefined values when functions are not yet initialized.
----
ℹ️ You need to test on WP5.9. Make sure to have a Stripe API Key for testing.
1. Insert a Stripe Checkout Block
2. It should work as expected.
----
> Fix undefined checking for stripe store in Stripe Checkout Block

- inc/integrations/api/form-response-data.php
- inc/server/class-form-server.php
- src/blocks/blocks/form/edit.js
Closes #1804
Added missing submit messages handlers.
----
1. Create a Form and set custom submit messages for Succes and Error in block Inspector.
2. Test the success message.
3. Try to break the form to get the error message.
ℹ️ If you do not want to go through the process of installing the SMPT for mail. You can activate otter pro and use save in `Database` to test the success message, then switch to `Email` for error. (You will get an error if you do not have the SMPT set up)
----
> Fix missing submit messages for Form

- src/blocks/components/image-grid/GridList.js
- src/blocks/components/image-grid/SortableList.js
Closes #1820 
🔴 I could not find how to fix this by tweaking the props of the HOC component.
🔧 The working solution was a manual cleaning of the extra nodes. It is a little hack, but it works.
https://github.com/Codeinwp/otter-blocks/assets/17597852/13213723-9892-4993-952d-d046d4afb93a
----
1. Create a Slider Block
2. Add images.
3. Sort the images using the Drag and Drop feature like in the video above.
----
> Remove extra nodes when sorting the images in Slider with drag-and-drop.

- src/blocks/blocks/countdown/inspector.js
- src/blocks/blocks/flip/inspector.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/icon-list/inspector.js
- src/blocks/blocks/icon-list/item/inspector.js
- src/blocks/blocks/popup/inspector.js
- src/blocks/blocks/review/inspector.js
- src/blocks/blocks/tabs/group/inspector.js
Closes #1781 
Removed extra words.
----
1. Create a Form Block
2. In Inspector/Sidebar, go to Style -> Helper & Submit Messages
----
> chore: remove extra wording in form

- src/blocks/blocks/circle-counter/inspector.js
- src/blocks/blocks/progress-bar/inspector.js
Closes #1753
Update the inspector/sidebar structure for Progress and Circle Block.
ℹ️ No new functionality has been added to the blocks.
https://github.com/Codeinwp/otter-blocks/assets/17597852/849b3896-c31d-403b-8913-a5c962539ea2
----
ℹ️ The PR https://github.com/Codeinwp/otter-blocks/pull/1814 was not yet merged. 
⚠️ The changes are only for Inspector; anything else should not be affected: behavior or functionality.
1. Create a Progress and a Circle Block.
2. Test the functions from Inspector.
----
> Revamp inspector for Progress & Circle

- src/blocks/blocks/slider/edit.js
Closes #1710 
- Tweaked the hook that re-initializes the Glide instance when the num of images changes. 
- Used a React Ref for getting the container for the Glide instance instead of making use of `querySelector`. This is working nicely in FSE and Widgets. But I still need the `querySelector` to check if the root is reachable by Glide -- e.g.: Inserter Block Review is not reachable.
- Solved another error related to the observer when deleting the block.
https://github.com/Codeinwp/otter-blocks/assets/17597852/f12770c2-695d-411d-9085-875ac2cbf6b7
----
1. Create a new Slider Block.
2. Add some images.
3. The arrows that change the image position should work.
----
> Fix slider error on Block creation

- src/animation/frontend.js
Closes Issue: (n/a)
Added `requestAnimationFrame()` API to scroll sniffing for better performance. Source: https://css-tricks.com/using-requestanimationframe/
_Edit by Hardeep:_ Details: https://wordpress.org/support/topic/performance-feature-request/#post-16998512
----
1. Add an animation to a black that is out of viewport `onLoad`.
2. Load the page with the animation. 
3. Ensure the animation fires appropriately
---- 
See [WordPress.org Support Thread](https://wordpress.org/support/topic/performance-feature-request/#post-16993761) for full context.
Please let me know if there are
> Adding requestAnimationFrame() to scroll sniffing for better perf

- inc/server/class-dashboard-server.php
Closes #1673
Added the `regenerate_styles` function in the hook that triggers when the theme changes.
----
1. Import content from Template Cloud. Change some blocks on the Home page.
2. When you change to a FSE theme, check the Home page frontend.
3. All changes made before changing the theme should be visible in the Frontend
----
> Regenerate saved style on theme change

- src/blocks/components/button-dropdown-control/editor.scss
- src/blocks/components/color-dropdown-control/editor.scss
Closes #1711
Updated the Section Color Dropdown Component selector regarding the alignment fix in Inspector for the Dropdown component.
Not the selector targets 5.x and 6.0 WP versions. ^6.1 will not be affected.
----
⚠️ We need to test backward compatibility with 5.9, 6.0, 6.1, 6.1
1. Insert a Section Block
2. Go to its color picker in Background & Content on the Style tab, and when pressing the change color, the Popover will be beside the Inspector. Not too further and not inside.
----
> fix: color section dropdown alignment selector

- inc/css/blocks/class-shared-css.php
- src/blocks/blocks/flip/inspector.js
- src/blocks/blocks/section/column/edit.js
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/edit.js
- src/blocks/blocks/section/columns/inspector.js
Closes #1723
- Added color extraction to Section Block & Column Block for Shadow Color from CSS vars when opacity is lower than 100%.
- Minor fix for Flip Shadow Color: it did not consider the new color when processing. 
https://github.com/Codeinwp/otter-blocks/assets/17597852/2b61b8f6-5f97-4f7f-8fb7-53ea5ec115d8
----
1. Insert a Section block with one Column Block.
2. Test the shadow in both blocks, like in the video above.
----
> Add CSS var conversion to hex for Section & Column Block shadow color

- inc/integrations/api/form-request-data.php
- inc/integrations/api/form-response-data.php
- inc/integrations/class-form-utils.php
- inc/integrations/interfaces/interface-form-subscribe-service.php
- inc/integrations/providers/class-mailchimp.php
- inc/integrations/providers/class-sendinblue.php
- inc/server/class-form-server.php
- src/blocks/blocks/form/edit.js
- src/blocks/test/e2e/blocks/form.spec.js
Closes #1835 
ℹ️ From the last Form update, the internal structure was slightly modified. The relaxed type hint from PHPDocs made the problem invisible to PHPStan.
🔩  The type hint is now more strict.
🐛 Improved error display in Editor.
🔧 Test Provider feature has been simplified.
https://github.com/Codeinwp/otter-blocks/assets/17597852/58e4e762-1b4e-4905-8b72-20c92a83cee4
----
⚠️ You will need a Mailchimp and Sendinblue API Key.
1. Insert a Form.
2. Go to marketing integration and use valid API Keys to check the functionality.
3. Try to use an invalid key format (like a random string) to see if errors appear as notices in the bottom-left corner.
----
> Fix Form Marketing List ID fetch and improve error handling

- src/blocks/blocks/form/common.tsx
- src/blocks/blocks/form/file/inspector.js
- src/blocks/blocks/form/hidden-field/inspector.js
- src/blocks/blocks/form/input/inspector.js
- src/blocks/blocks/form/multiple-choice/inspector.js
- src/blocks/blocks/form/textarea/inspector.js
- src/blocks/frontend/form/index.js
- src/pro/blocks/file/inspector.js
- src/pro/blocks/form-hidden-field/inspector.js
- src/pro/plugins/form/index.js
Closes #
Attach docs link to the Mapped Name field in Fields Blocks.
Enable the change of the mapped name in Hidden Input.
----
----
> Attach Themeisle docs link on Mapped Name

- src/blocks/plugins/options/index.js
Closes #1812
The current handling of the case for the user who did not have the right to write to modify the options was very minimal.
🔧 Add conditional statements that hide the options from which the users do not have permission.
----
1. Enter as a non-administrator user.
2. Create a new post and check the otter options in the top-right corner.
3. You should see only the onboarding Modal and Feedback.
⚠️ If you make a particular user with the rights to modify WP Options (like admin), then you should see the full options.
----
> Fix Otter options infinite loading

- inc/server/class-prompt-server.php
- src/blocks/blocks/content-generator/editor.scss
- src/blocks/components/prompt/index.tsx
Closes #.
Added consent toggle for AI Block. The consent uses the already present value of `'otter_blocks_logger_flag'`
Behaviour:
- Toggle will not appear for people who have already accepted.
- If the button close is used, we will use the browser storage to store the preference. The toggle will reappear if the user cleans up the values or uses another browser.
----
⚠️ You will need an OpenAI Key.
1. Create an AI Block and make a first request.
2. When the request is done, the consent toggle should appear.
3. If you press the Close button, the toggle should appear when you make another block. If you change the browser, the toggle should be visible since this is working at the browser level.
4. If you accept the consent, the toggle will disappear, and it will not be visible even if you …
> Add AI Block consent toggle

- inc/render/class-review-block.php
- src/blocks/blocks/review/block.json
- src/blocks/blocks/review/inspector.js
- src/blocks/test/e2e/blocks/product-review.spec.js
Closes #1840
🔩 Added the option to open the links in the same tab.
ℹ️ Default behavior opens in the new tab to preserve the current status.
----
1. Create a Product Review Block
2. Check the options that allow you to open the link in the same or a new tab (Inspector > Settings > Buttons)
----
> Open in new tab for Review Block links

- inc/class-registration.php
Closes #1665
Using `'dynamic_sidebar_params'` we can identify the used widgets in the page. The great changes is that we need to run the assets loading in `wp_footer` since that filter will not run during `'enqueue_block_assets'`.
https://github.com/Codeinwp/otter-blocks/assets/17597852/1576d926-6429-409c-a259-7735480fdfae
----
ℹ️  Use a classic theme like Neve.
1. In the widgets page, add blocks like Maps, Google Maps, and progress bar in different parts of the widgets section.
2. Insert a widget in a page and ensure the scripts from another widget section are not loaded.
3. If you a have widget with a Maps block that load `leaflet.js` and is not present in page, then that script should be loaded.
----
> Remove unnecessary deps when using widgets

- src/animation/frontend/typing/index.js
- src/blocks/test/e2e/blocks/animations.spec.js
Closes #1717
Now, the typing animation will respect the text color.
https://github.com/Codeinwp/otter-blocks/assets/17597852/974a3c85-8b9e-4936-bd5d-48951833165b
----
1. Create a paragraph and set a color.
2. Add typing animation.
3. See if it keeps the colors.
Sample
```html
<p class="o-typing-delay-500ms has-vivid-red-color has-text-color">Placerat habitasse commodo ante hac erat diam vehicula in porttitor. Ridiculus facilisis cursus inceptos orci dis faucibus neque justo curae. Mattis velit et accumsan sapien justo vivamus si. Netus hac fames aliquam ullamcorper convallis est habitasse letius molestie phasellus dui. Elit per adipiscing sodales nascetur est turpis vel curabitur. <o-anim-typing>Sapien quam class vel luctus a sagittis ad pellentesque. Viverra consectetur montes rhoncus …
```
> Do not ignore CURSOR color during typiing anim

- plugins/otter-pro/inc/plugins/class-live-search.php
Closes #91
Wrap the live-search deps with a wp action named: `otter_load_live_search_deps`
If you want to load Live Search functionality in your custom theme or 3-rd party plugin. Use the wordpress action `otter_load_live_search_deps`.
Example:
```php
do_action( 'otter_load_live_search_deps' );
```
ℹ️ This feature can only be used by Otter Pro users.
----
This is a dev-only change. The Libe Search should work as expected. 
----
> Load Live Search deps via WordPress Action Hook

- inc/class-blocks-css.php
- inc/class-registration.php
- inc/css/class-block-frontend.php
Closes #1880
Use `empty` function for content checking instead of `isset`.
----
Minor dev changes. Everything should work without no issue.
----
> fix: phpstan issues

- .github/workflows/e2e-js.yml
- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/blocks/advanced-heading/inspector.js
- src/blocks/components/typography-selector-control/editor.scss
- src/blocks/components/typography-selector-control/index.tsx
- src/blocks/test/e2e/blocks/heading.spec.js
Closes #1882
Moved the old typo component to the new one.
Development notes: It was not a smooth experience, but I was glad to find a new trick to tackle the responsive option.
Before
After
----
⚠️ Before using this build, make some Heading blocks with the current version and customize them with Typography.
Switching to the PR build and checking if the options are the same as before and if they are working like before.
----
> Improve Heading typo component

- webpack.config.js
Closes #1876 
`wp-scripts` automatically gathers all `.json` files and puts them inside each build.
Reference: https://github.com/WordPress/gutenberg/blob/1fb1343c42a59d5062660a7da20a4bff4d06e369/packages/scripts/config/webpack.config.js#L263-L313
ℹ️ By using the already existing FIleManager in our setup, we can delete the extra file generated.
Output of `tree build -d`
After change:
```
build
├── animation
│   └── images
├── blocks
│   ├── about-author
│   ├── accordion
│   ├── accordion-item
│   ├── advanced-column
│   ├── advanced-columns
│   ├── advanced-heading
│   ├── button
│   ├── button-group
│   ├── circle-counter
│   ├── content-generator
│   ├── countdown
│   ├── flip
│   ├── font-awesome-icons
│   ├── form
│   ├── form-file
│   ├── form-hidden-field
│   ├── form-input
│   ├── …
```
> Remove extra files from build

- inc/plugins/class-dashboard.php
- plugins/otter-pro/inc/plugins/class-form-emails-storing.php
- src/blocks/test/e2e/blocks/form.spec.js
Closes #1671
Add a button that exports the form submission in XML format via `export_wp`.
https://github.com/Codeinwp/otter-blocks/assets/17597852/141bc427-c7c0-422a-81f3-de5143c01ebd
----
1. Make some submissions.
2. Try Export them via any method. Our button, or native one, via Tools > Export. Or any popular plugin for exporting WP pots or pages.
----
> Add Form Submission Export

- inc/class-blocks-animation.php
- src/animation/data.js
- src/animation/editor.js
- src/animation/editor.scss
- src/animation/frontend.js
- src/blocks/helpers/block-utility.js
- src/blocks/helpers/blocks.d.ts
- src/blocks/test/e2e/blocks/animations.spec.js
Closes #1548
🚀 Now, users can use custom values for Speed and Delay
🔍 Now, animations can trigger on mouse hover.
⛔ Offset for triggering the animation after passing a certain point.
----
1. Make a block and add an Otter animation via the Block Tools tab on the Sidebar/Inspector
2. Check if the custom values, offset and hover are working.
⚠️ Hover is *not* enabled for the Editor to preview.
⚠️ The reference point for offset is considered the top limit of the element. If you use an image as a test, do think that the middle of the image is the reference point when you set the value of the offset. If you want to trigger the animation when the image is fully visible, use the image width as the offset.
Also, make sure that CSS class names for the block that you are testing look clean, like …
> Animation enhancements

- inc/css/blocks/class-posts-css.php
- inc/css/class-css-utility.php
- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/block.json
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/edit.js
- src/blocks/blocks/posts/inspector.js
- src/blocks/blocks/posts/style.scss
- src/blocks/blocks/posts/types.d.ts
- src/blocks/helpers/helper-functions.js
Closes #1046
Add pagination for Posts Block.
Developing notes:
- It seems that Dynamic Content collides with the counting mechanism. It needs some investigation on the cause.
https://github.com/Codeinwp/otter-blocks/assets/17597852/9bdbff2e-11cb-457d-8271-2a2572167e12
----
1. Insert a Post Block
2. Enable pagination and customize it.
----
> Add Pagination for Posts

- inc/class-registration.php
Closes #1931 
It seems that there are more than one executions of https://github.com/Codeinwp/otter-blocks/blob/3ed5af1cc875b2fba08690228e6ef3d0f1bc0cb5/inc/class-registration.php#L991
Each execution overrides the previous one. Since the detected widgets were cleaned off the first execution, the next one overrides the previous but without the content of widgets since the variable that was holding the detected widgets is not empty.
⚠️ There might be some changes in WP since when it was added it worked fine when it was added. 
----
1. Check if block styles are loaded on the page when blocks are in widgets.
----
> Do not clean detected widgets on widget content detection

- src/blocks/frontend/live-search/index.ts
- src/blocks/test/e2e/blocks/live-search.spec.js
Closes #1930
Initialize live search when the block is visible. Add an E2E case for it.
----
1. Insert a Popup block, then put a Live Search on it.
2. Check if the results are visible.
----
> Fix Live Search initialisation inside containers like Popup Block

- src/blocks/blocks/posts/edit.js
Closes #1955
Make the custom `'rank_math_content'` filter to return its given content by params.
⚠️ It seems that not given the original content made some condition to show negative. 
Without Otter
Current version
With fix
----
1. Install MathRank
2. Make a page and check the store.
3. Install Otter with the fix and score that should remain the same or go higher*.
*The code was initially added to detect Post blocks. Check this https://github.com/Codeinwp/otter-blocks/pull/1874
----
> Prevent rank math filter to erase previous content

- inc/integrations/class-form-utils.php
Closes #1933
Removed the obsolete checking for Files. New versions of PHP are smarter at detecting minor issues/
----
Test with an instance with a version of PHP at least 8.
ℹ️ This will require Otter Pro
1. Create a Form Block with a File Field.
2. Send some files and check if everything is alright regarding the files.
----
> Remove obsolete base64 checking in Form File validation

- docs/coding-best-practices.md
- src/blocks/helpers/use-settings.js
- src/blocks/plugins/ai-content/index.tsx
- src/blocks/plugins/options/index.js
Closes #1973.
The useSettings hook repeated calls to settings API after a recent version, probably after AI Content creator as that hooks to function to each block.
After trying various methods, I settled on this one as it seems to work with all the current usage of useSettings that we have in Otter.
I also tried to use a better implementation but those seem to not always work with the various use cases that we have with Otter. (as in using the Data Store for saving/retrieving the data)
In the future, I'd avoid using useSettings in plugins as now Gutenebrg has built-in methods to use Settings API from the store, and as we work on different parts of Otter, we can try to remove the existing usage of useSettings.
- Try using Otter blocks and Patterns and make sure the calls to Settings route …
> fix: otter making repeated api calls

- src/blocks/blocks/button-group/button/save.js
Closes #2009.
Seems like WordPress started to add noopener rel to all links that have a target attribute that is breaking Button Group block. This PR makes sure to account for that.
- Create a button group with few buttons with norel enabled and disabled.
- Save the post and refresh to make sure it doesn't break after using this version.
- It should also fix any blocks that have previously been saved.
----
> fix: button group breaking when nofollow isn't being used

- inc/class-registration.php
- tests/test-block-conditions.php
Closes #2001.
Fixes the issue with Block Conditions causing a PHP error in certain cases.
- Make sure Block Conditions, specially if Device Visibility conditions are used, don't throw any PHP errors in debugging logs.
----
> fix: undefined array key in block conditions

- inc/class-registration.php
- inc/css/class-block-frontend.php
- inc/css/class-css-handler.php
Closes Codeinwp/neve#4150.
The condition for enqueueing frontend styles for the widgets blocked the styles from registering.
----
1. Use Neve
2. Add Otter blocks to the footer widget area
3. Customize the widgets with styles
4. Check that the styles are preserved on the frontend.
----
> fix: widget_styles

- .wp-env.override.json
- inc/plugins/class-fse-onboarding.php
- inc/plugins/class-options-settings.php
- src/onboarding/store.js
Fixes post-release issues found here: https://github.com/Codeinwp/raft/issues/99
- Fix imported items array being a value of only booleans in tracking data.
NO
- Make sure tracking data in MongoDB is for imported_items is recorded correctly.
Closes #99.
----
> fix: onboarding imported_items tracking

- src/blocks/editor.scss
- src/blocks/helpers/block-utility.js
- src/blocks/plugins/conditions/edit.js
- src/blocks/plugins/otter-tools-inspector/index.tsx
Closes #2021.
Fix styling conflict with third-party plugins.
----
- Make sure the styling issue described in the issue aren't there anymore.
---- 
- [] Visual elements are not affected by independent changes.
> fix: style conflict with third-party plugins

- src/pro/plugins/conditions/edit.js
Closes #2018.
This PR fixes the change in Woo rest route that requires the per_page attribute to be 0 instead of -1 to display all products.
----
- Make sure Block Conditions' Product conditions work.
----
> fix: fix woo products not appearing in block conditions

- src/blocks/blocks/form/edit.js
Closes #1978.
Fixes an issue when form submit button accepts line-breaks in the editor.
----
- Make sure Submit button doesn't accept line breaks in the editor.
----
> fix: form submit button accepting linebreaks

- src/animation/frontend.js
Closes #2005.
It fixes an issue when animation isn't triggered for large elements that are in the viewport with their top and bottom being outside the viewport.
----
- Create a page and add the whole content in a group block
- Add a loading animation to the group block (Fade in for example)
- Scroll to the middle of the page and reload
- Make sure it animated
----
> fix: animation not trigger for large elements on screen

- src/blocks/frontend/leaflet-map/index.js
Closes #2053.
Adds a resizer-observer to Leaflet Maps block to fix an issue with Tabs not rendering Map Block properly.
----
- Add Maps Block to a Tab
- Load in frontend and resize the window.
----
> fix: resize leaflet maps on resize

- src/blocks/index.js
- src/blocks/plugins/dynamic-content/media/index.js
- src/dashboard/index.js
Closes #2047.
Replace ReactDOM.render to use createRoot instead to remove console errors.
----
- Make sure you don't see any errors in console when you use Otter.
-->
----
> fix: update to use createRoot instead of render

- webpack.config.plugins.js
- webpack.config.pro.js
Closes #2058.
Fixes the issue where build files include files from other build folders.
----
After setting up the plugin, run npm run build & npm run dist, you will notice block plugins have pro and blocks files from other plugins.
----
> fix: build including duplicate files

- inc/plugins/class-fse-onboarding.php
- src/onboarding/components/Finish.js
- src/onboarding/components/Sidebar.js
- src/onboarding/components/Start.js
- src/onboarding/style.scss
Closes https://github.com/Codeinwp/otter-internals/issues/141.
Adds option to display the logo of the theme if provided in the theme support.
----
- Follow here: https://github.com/Codeinwp/raft/pull/103
----
> fix: add logo option to onboarding

- composer.json
- composer.lock
- inc/integrations/class-form-utils.php
Closes #152.
Introduces the SVG Sanitize to sanitize SVG files to prevent XSS attacks.
- Make sure SVG uploads work as expected.
- Make sure the issue mentioned in the issue is solved.
----
> fix: introduce svgSanitize to sanitize SVG

- inc/render/class-form-multiple-choice.php
- plugins/otter-pro/inc/render/class-form-file-block.php
- plugins/otter-pro/inc/render/class-form-hidden-block.php
Closes https://github.com/Codeinwp/otter-internals/issues/153.
Hardens escaping of attributes in Pro Form fields. The PR also makes use of `get_block_wrapper_attributes` function for attribute generation for the main div of the block.
----
- Follow testing instructions mentioned in the issue and confirm the issue is mitigated, and features work as normal.
----
> fix: hardened escaping inside Pro Form Fields

- inc/plugins/class-limited-offers.php
- src/dashboard/components/Main.js
Close https://github.com/Codeinwp/themeisle/issues/1613
The data of the event is now controlled by the SDK
⚠️ The promo in the settings dashboard will not appear if you already have Otter Pro
- Should be testing using this version of SDK: https://github.com/Codeinwp/themeisle-sdk/pull/208
- You should see the banner in Otter Blocks > Settings when you set your date to match the black Friday campaign (Read in the PR above).
- Outside the campaign, it should not be visible
----
> Prepare for Black Friday 2024

- inc/render/class-google-map-block.php
Closes #.
Ignore for now, just doing it for generating build.
----
----
> fix: escape ID in Maps

- inc/plugins/class-dashboard.php
Closes https://github.com/Codeinwp/neve-fse/issues/116.
Fixes the issue with nps survey appearing in new installs when the plugin is downloaded programmatically.
----
> fix: nps survery appearing on new installs

- inc/render/class-leaflet-map-block.php
- inc/render/class-masonry-variant.php
- inc/render/class-posts-grid-block.php
- inc/render/class-review-block.php
- inc/render/class-stripe-checkout-block.php
- package-lock.json
- package.json
Closes https://github.com/Codeinwp/otter-internals/issues/158, https://github.com/Codeinwp/otter-internals/issues/159.
- Escape block attributes in SSR
- Update Formbricks library
> Escape block attributes to avoid bad-faith actors

- src/blocks/blocks/section/column/block.json
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/block.json
- src/blocks/blocks/section/columns/inspector.js
- src/blocks/test/e2e/blocks/section.spec.js
Closes #2148.
Fixed the range control when first adding the section block for the margin and padding.
Added e2e test for this behavior.
----
1. Add a Section block with one Column
2. Add a paragraph in that Column
3. Try to add a Margin or Padding using the slider control, not entering the numeric value
4. E2E tests should pass
----
> fix: margin and padding range for section block

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/components/layout/index.js
- tests/test-post-grid-block.php
Closes https://github.com/Codeinwp/otter-internals/issues/165
Added better sanitation function for `titleTag` attribute.
1. Create a new post.
2. Use Code Editor instead of Visual Editor.
3. Paste the code below into the page and check if the alert starts when you hover the mouse over the title. If the alert start, the issue was not fixed. 
```html
```
On the page, you should see this HTML output: 
This means sanitation succeeded, and somebody tried to create an XSS attack from a compromised account.
----
> Improve Posts block output sanitization

- inc/plugins/class-block-conditions.php
- src/blocks/test/e2e/blocks/block-conditions.spec.js
- src/blocks/test/e2e/utils.js
Closes #2191 
Because the function `render_blocks` for block conditions could not return anything, an error is raised because the filter `render_block` must return a string.
I refactored the function so that it always returns a string. Also, change from `add_action` to `add_filter` since `render_block` exists as a filter, and with the new phpdoc added to the function, phpstan does not allow us to use the `add_action` since we are always returning something. 
> [!NOTE]
> By being aware of https://github.com/Codeinwp/otter-blocks/issues/2177, in this PR, the introduced test is critical to succeed.
----
1. Use Otter Free.
2. Create a new post and insert an Image Block
3. Set the condition to be visible to the Logged User.
4. Check the page if the block is rendered. 
5. Log out, then recheck …
> fix: enforce display condition to return string in `render_block` filter

- src/blocks/plugins/upsell-block/index.js
Closes #2193 
Each pattern has an Upsell Notice embedded. If there are multiple notices, they are removed except the first one.
The condition that checked if the block is rendered inside the editor was using `document.querySelected` and evaluated before the rendering, thus making it to be always false.
By moving the check inside the `effect`, we fix this problem since the hook runs after the component is rendered on the page.
----
https://github.com/Codeinwp/otter-blocks/assets/17597852/3c7de8dd-1ad9-4f78-9f38-f4b89162a7c2
1. Use Otter Free
2. Insert many patterns
3. You should see only one Upsell Notice block like in the video
----
> Fix pattern upsell show condtion

- inc/class-registration.php
- plugins/otter-pro/inc/server/class-live-search-server.php
- tests/test-live-search.php
Closes https://github.com/Codeinwp/otter-internals/issues/166
Filter out any non-searchable post type from the Live Search Block.
Users who want their post type to appear in the search must register their post type with `public` set to `true` and `exclude_from_search` set to `false`.
```php
register_post_type( 'my_post_type', array(
'public' => true,
'exclude_from_search' => false,
'label'  => 'My Post Type',
) );
```
----
1. With Otter Pro, insert a Search Block and activate the Live Search
2. In the post types, you should see only the searchable post types ( they are registered as public and not excluded from search query )
----
> Use only searchable post type for Live Search

- inc/class-registration.php
- src/blocks/blocks/form/edit.js
- src/blocks/frontend/form/index.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2212
Fix the typo on the privacy statement for Form Block Marketing Integration.
----
1. Insert a From block
2. Activate marketing integration for Mailchimp or Sendinblue
3. Select `Submit & Subscribe` as action.
----
> fix: form privacy statement typo

- src/blocks/blocks/posts/components/layout/index.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2183
Added a decoder for the entities in the categories. 
The Gutenberg API sends encoded entities when requesting categories. So `Click & Go` becomes `Click &Amp Go`. Construction like `Click&Go` or `Click&` are unaffected; only isolated `&` are encoded.
----
1. Create a category named `Click & GO`. 
2. Attach it to some posts.
3. Make a new post, insert the Post block, and filter by this category.
----
> fix: decode entities for post block category

- inc/css/blocks/class-button-group-css.php
- src/blocks/blocks/button-group/group/inspector.js
- src/blocks/test/e2e/blocks/block-conditions.spec.js
- src/blocks/test/e2e/blocks/button-group.spec.js
- src/blocks/test/e2e/utils.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2163
- Fixed the wrong connection between font properties
- Fix the text line height value to be the same as in the Editor
- Added an E2E test.
> [!NOTE]
> Be aware of https://github.com/Codeinwp/otter-blocks/issues/2177
----
- Insert a Button Group block
- Modify the value in Typography tab
- Check if they correspond in the front end. 
----
> Fix Buton Group Font settings

- src/blocks/frontend/form/index.js
Closes https://github.com/Codeinwp/otter-internals/issues/186
Remove the field number when sending the data.
----
> [!NOTE]
> You must set up an email service so that `wp_mail` can work.
1. Make a simple Form block
2. Send some data and check if the field number is not longer present.
----
> fix: remove field number

- .wp-env.override.json
- bin/e2e-tests.sh
- src/blocks/blocks/content-generator/block.json
- src/blocks/blocks/content-generator/edit.js
- src/blocks/blocks/content-generator/types.d.ts
- src/blocks/plugins/ai-content/index.tsx
- src/blocks/test/e2e/blocks/ai-block.spec.js
Closes https://github.com/Codeinwp/otter-internals/issues/214
The origin block in which the AI actions are triggered is now linked to the AI Block created. On Replace actions, the origin block will be replaced, and the AI Block will be deleted.
> [!NOTE]
> This works when both blocks are part of the same session. It is considered a new session if you reload the page or switch to code mode and come back.
https://github.com/user-attachments/assets/33448ebe-5a18-4e9b-8561-fe2a5558a271
----
> [!NOTE]
> You will need an OpenAI key.
1. Use the actions AI Toolbar from a paragraph block.
2. Click `Replace` after the AI Block generates the content.
3. The original block should be replaced.
----
> fix: replace the original block of the AI Toolbar action

- src/animation/index.js
- src/blocks/plugins/conditions/index.js
- src/blocks/plugins/options/index.js
- src/css/index.js
Closes https://github.com/Codeinwp/otter-internals/issues/183
Made additional the modules enabled again.
----
Check if the modules are enabled again.
----
> fix: enable additional modules by default

- otter-blocks.php
Closes https://github.com/Codeinwp/otter-internals/issues/210
Added Welcome Upsell notice from SDK.
----
1. Install Otter
2. Make the Otter plugin install time to be older than 7 days and newer than 14 days.
3. Check if the notices shows up
You can directly edit the install date in `/admin/options.php`. You can this website to generate the date value: https://www.nexcess.net/web-tools/unix-timestamp-converter/ (Set the date with 8 days back from the current one)
----
> feat: add 7 days notice for upsell

- src/blocks/components/prompt/editor.scss
Closes https://github.com/Codeinwp/otter-internals/issues/117
On the wide mode, center the block. 
----
1. Insert an AI Block
2. Set the block to `Wide` using the toolbar
3. Check if it centered
----
> fix: AI Block container alignment

- src/blocks/frontend/accordion/index.js
- src/blocks/frontend/tabs/index.js
- src/blocks/helpers/frontend-helper-functions.js
Closes https://github.com/Codeinwp/otter-internals/issues/193
If the tab that is going to be open is not visible after the others are closed, scroll to it.
https://github.com/user-attachments/assets/da76e3df-3a96-4289-8fad-aaac75199b88
https://github.com/user-attachments/assets/553cd180-dde1-428b-ad43-d6190f31e8be
----
1. Insert some huge paragraphs.
2. In the middle add an accordion and a tab block
3. Fill him also with huge content.
4. When you open a tab, it should make sure that the beginning is always visible like in the video
----
> fix: auto scroll for tabs and accordion on opening

- inc/class-registration.php
- inc/plugins/class-options-settings.php
- src/blocks/global.d.ts
- src/blocks/plugins/ai-content/index.tsx
- src/blocks/test/e2e/blocks/dashboard.spec.js
- src/dashboard/components/pages/Dashboard.js
Closes https://github.com/Codeinwp/otter-internals/issues/206
Added a toggle for the AI Toolbar similar to the CSS module.
----
1. Check the dashboard for the new toggle.
2. Toggle it off, then check the Paragraphs block in the Post. It should be hidden.
3. Re-enable the option and check again.
----
> Add AI Toolbar visibility toggle in Dashboard

- src/blocks/blocks/popup/editor.scss
Closes https://github.com/Codeinwp/otter-internals/issues/217
I added a minimum height of `450px` in the Popup edit area.
----
Insert a Popup Block, click the `Edit` button, and see if you find the new height more ergonomic.
----
> fix: increase the height for Popup in Editor on auto mode

- src/blocks/plugins/dynamic-content/editor.scss
- src/blocks/plugins/dynamic-content/link/edit.js
- src/blocks/plugins/dynamic-content/value/edit.js
Closes https://github.com/Codeinwp/otter-internals/issues/208
This moves the Dynamic Link and Value from Format Dropdown to the main toolbar to improve visibility. It also changes the icon for Dynamic Link to avoid confusion.
----
- Confirm the feature works as before with the new UI.
----
> Experiment with formats in the toolbar

- inc/class-patterns.php
- inc/plugins/class-dashboard.php
- src/blocks/blocks/countdown/edit.tsx
- src/blocks/blocks/countdown/inspector.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/slider/block.json
- src/blocks/blocks/slider/edit.js
- src/blocks/blocks/slider/index.js
- src/blocks/components/notice/editor.scss
- src/blocks/editor.scss
- src/blocks/helpers/icons.js
- src/dashboard/components/pages/Blocks.js
Closes https://github.com/Codeinwp/otter-internals/issues/173.
- Rename Slider to Image Slider
- Remove notice from Countdown Block
- Change upsell notice color to Gray
- Remove Upsell from Form sidebar
- Add Pro label to Form Submission menu item
- Remove Export button from Form Submission page for in free version
- Rename sib to Brevo
- Remove CTA category, use the default one
- Replace webhook docs link
- Set default Countdown date
----
----
> chore: various small changes

- Gruntfile.js
- bin/dist.sh
- plugins/blocks-animation/blocks-animation.php
- plugins/blocks-animation/composer.json
- plugins/blocks-animation/composer.lock
Closes https://github.com/Codeinwp/otter-internals/issues/196
The PR adds ThemeIsle SDK to Blocks Animation child-plugin.
----
- Make sure the SDK works and doesn't throw any issues when used with or without Otter.
----
> feat: add themeisle-sdk to Blocks Animation

- src/blocks/plugins/dynamic-content/value/autocompleter.js
Closes https://github.com/Codeinwp/otter-internals/issues/207
This changes the current autocomplete behavior for Dynamic Value from displaying Free first and Pro later to mix them.
----
- Confirm the feature works as before, and you see a mix of Free/Pro by default.
----
> feat: display a mix of free/pro in autocomplete

- src/blocks/blocks/slider/editor.scss
Closes https://github.com/Codeinwp/otter-internals/issues/190.
This fixes the issue with Slider not working properly in the editor when added inside the Section's Column.
----
- Add a section block with 2 columns
- In the first column, add a slider block
- In the second one, add a paragraph block
- Save and check the page
- Also, adjust the column width and check again
----
>  fix: slider breaking when inside a Section Column 

- inc/class-registration.php
Closes https://github.com/Codeinwp/otter-internals/issues/121.
This fixes the issue with CSS not being applied instantly to blocks added to Widgets in the Customizer or Widgets area.
Previously, it worked if you made another change and Published your changes from the Customizer, but the current block status wasn't taken into consideration.
We remove the previously implemented `wp_registered_widgets` check as we are already using `$widgets_used` to check for inactive widgets.
----
- Add some blocks as widgets from Customizer and publish the change.
- Confirm the CSS is applied properly after the very first publish attempt.
- Also confirm in the generated CSS file that no CSS is generated if the block is part of Inactive Widgets screen.
----
> fix: styles not applying on blocks added to widgets

- src/blocks/frontend/popup/popup.ts
- src/blocks/test/e2e/blocks/popup.spec.js
Closes https://github.com/Codeinwp/otter-internals/issues/204
The popup will close on the ESC key press.
----
1. Create a Popup Block
2. Check in preview
3. Press on ESC key close it.
----
> feat: close popup on ESC key

- inc/css/blocks/class-flip-css.php
Closes https://github.com/Codeinwp/otter-internals/issues/187
Fix incorrect name for variable identification for image background size on Flip Block PHP CSS.
----
1. Insert a Flip Block
2. Add **small images** as background for the front and back sides
3. Check if the settings are applied.
----
> fix: incorrect name for background size on Flip Block php css

- src/blocks/blocks/section/column/block.json
- src/blocks/blocks/section/column/inspector.js
- src/blocks/blocks/section/columns/block.json
- src/blocks/blocks/section/columns/inspector.js
- src/blocks/test/e2e/blocks/section.spec.js
Closes https://github.com/Codeinwp/otter-internals/issues/184
- Removed the default attributes value for table and mobile so users can use `0px` values
- Improved the inheritance behavior using a desktop default value for Inspector components to prevent a null state on the slider.
https://github.com/user-attachments/assets/8c1ffc11-ef77-49c2-b97e-8a4ac8fd4e99
----
1. Insert a Section Block
2. Change the padding and margin in Desktop view
3. Go to Mobile view and set it to `0px`. It should work.
4. Reset and the values should be back to the one in Desktop view
----
> fix: Section block default inheritance for margin and padding

- src/blocks/plugins/registerPlugin.tsx
Closes https://github.com/Codeinwp/otter-internals/issues/213.
As we discussed, this PR disables Copy/Paste Styles features for the time being. We still keep the code inside, just disable the feature.
----
- Confirm Copy/Paste styles toolbar doesn't appear anymore.
---- 
- [] Included E2E or unit tests for the changes in this PR.
> chore: disable copy/paste styles feature

- inc/class-blocks-css.php
- src/css/editor.js
- src/css/index.js
Closes https://github.com/Codeinwp/otter-internals/issues/120 and https://github.com/Codeinwp/otter-internals/issues/194.
This adds a Notice to Site Editor when Blocks CSS is being used alone. Clicking on the button installs to Otter in a new tab.
----
- Confirm the notice appears if:
- When using Blocks CSS in Site Editor
- Not inside normal Post Editor or when used as part of Otter 
----
> feat: add Otter notice in FSE editor for Blocks CSS

- .gitignore
- composer.json
- composer.lock
- inc/plugins/class-block-conditions.php
- plugins/otter-pro/inc/plugins/class-block-conditions.php
- src/blocks/plugins/conditions/edit.js
- src/pro/plugins/conditions/edit.js
- src/pro/plugins/conditions/index.js
- tests/bootstrap.php
- tests/test-block-conditions.php
- tests/test-woo-conditions.php
Closes https://github.com/Codeinwp/otter-internals/issues/198.
This PR adds:
- Product Category
- Product Tag
- Product Attribute
conditions to Block Conditions module.
----
- You can import WooCommerce's sample data to get a good set of products.
- Confirm all the conditions work when the taxonomy is present/absent.
- There are no debugging errors.
- This is made for Product Page, so you must be using a FSE theme for being able to customize the Single Product Template.
----
> feat: add more Woo conditions to Block Conditions module

- inc/render/class-posts-grid-block.php
Closes https://github.com/Codeinwp/otter-internals/issues/128.
Like Core, we use the post title as the default alt for the Featured Images if the image doesn't have an alt specified.
----
- Make sure the behavior specified in the description is followed. The image alt gets the priority over post title.
----
> feat: use post title as alt if no image alt available in Posts Block

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/block.json
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/edit.js
- src/blocks/blocks/posts/inspector.js
- src/blocks/blocks/posts/style.scss
- tests/test-post-grid-block.php
Closes https://github.com/Codeinwp/otter-internals/issues/220.
- Change default block style to Boxed
- Change default heading to h4
- Change the default color, border, and number of posts
----
- Confirm all the described changes
- Most importantly, make sure the default style of new block is Boxed but it shouldn't affect existing blocks.
----
> feat: posts block improvements

- src/blocks/blocks/advanced-heading/style.scss
Closes https://github.com/Codeinwp/otter-blocks/issues/2299.
Adds more selectors to make sure Heading block works better with more themes as some themes and Core has some styles that prevent the default styles from working.
---- 
- [] Included E2E or unit tests for the changes in this PR.
- [] Visual elements are not affected by independent changes.
> fix: add more selectors for Advanced Heading

- inc/css/blocks/class-posts-css.php
- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/block.json
- src/blocks/blocks/posts/components/layout/featured.js
- src/blocks/blocks/posts/components/layout/index.js
- src/blocks/blocks/posts/components/layout/thumbnail.js
- src/blocks/blocks/posts/components/sortable.js
- src/blocks/blocks/posts/constants.js
- src/blocks/blocks/posts/edit.js
- src/blocks/blocks/posts/inspector.js
- src/blocks/blocks/posts/style.scss
- src/blocks/blocks/posts/types.d.ts
- tests/test-post-grid-block.php
Closes https://github.com/Codeinwp/otter-internals/issues/218.
Added a tiled style with overlay color and image as the background of the tiles as a new style to Posts Block.
----
- Just confirm everything works fine with the new style.
----
> feat: add tiled style to Posts Block

- src/blocks/blocks/advanced-heading/edit.js
- src/blocks/components/html-anchor-control/index.js
- src/blocks/helpers/block-utility.js
Closes https://github.com/Codeinwp/otter-internals/issues/201.
This disallows the Anchor Control from allowing an empty ID, as well as some changes in the blockInit function to rewrite existing empty IDs with a unique one.
----
- Confirm you can't change the ID of Section or Advanced Heading Block to an empty field.
- Confirm if you upgrade from an older version and open the editor, all empty sections get an unique ID.
----
> fix: disallow anchor control for using empty ID

- inc/integrations/api/form-request-data.php
- inc/integrations/api/form-response-data.php
- inc/server/class-form-server.php
Closes https://github.com/Codeinwp/otter-internals/issues/176
- Improved the error messages when the tester is an admin.
- Added error log step for warnings.
- Code refactoring
We are dumbing the error along with the requested data:
```
[23-Jul-2024 07:57:13 UTC] [Otter Blocks][Form Block] Issue: Email could not be send. Might be an error with the service. The function `wp_mail` is not working properly. Please check the email provider settings.| Form data received: {"form_data":{"handler":"submit","payload":{"formInputsData":[{"label":"Form submission from","value":"http:\/\/localhost:10005\/form-block\/","metadata":{"position":"0"}},{"label":"(Field 1) Name","value":"yes","type":"text","id":"wp-block-themeisle-blocks-form-input-d8b68920","metadata":{"version":"1","position":"1","mappedNam …
```
> Improve issue handlers for Form submissions

- plugins/otter-pro/inc/plugins/class-live-search.php
- plugins/otter-pro/inc/server/class-live-search-server.php
- src/blocks/components/index.js
- src/blocks/frontend/live-search/index.ts
- src/blocks/plugins/conditions/edit.js
- src/pro/plugins/live-search/edit.js
- tests/test-live-search.php
Closes https://github.com/Codeinwp/otter-internals/issues/142.
Live Search now allows you to search posts within categories if the selected post type in Post. This doesn't work with CPTs or custom taxonomies, only Post.
----
- Confirm the Search within category works fine if the Post type is selected.
- Also confirm it works when no types or random post types are selected.
----
> feat: add search within category to Live Search for Posts

- src/blocks/blocks/button-group/button/edit.js
- src/blocks/blocks/button-group/style.scss
Closes https://github.com/Codeinwp/otter-internals/issues/223.
This PR adds a default style for the block variations to prevent them from looking bad in the editor/front after the latest WordPress update. This breaks the history of the button inheriting the styles, which isn't possible after the latest WordPress update.
By adding the default styles, we ensure the buttons look at least presentable for users so they can customize them as needed.
----
- Make sure the buttons look good in some of the most popular themes.
----
> fix: button block appearance in latest wp version

- inc/integrations/api/form-response-data.php
- inc/integrations/providers/class-mailchimp.php
- src/blocks/blocks/form/common.tsx
- src/pro/blocks/form-stripe-field/inspector.js
Closes https://github.com/Codeinwp/otter-internals/issues/168
Added the ability to link the value of the fields with **some** of the types for Mailchimp Merge Fields
> [!NOTE]
> The users are advised to mostly use the type `TEXT` for the linked fields.
Fields like File do not file, but the name of the files. Select type fields (e.g., checkbox) and send a string of values with the selected types.
This is not made to handle complex cases, uploading files to Mailchimp, and advanced selection to their dropdown.
> [!WARNING]
> The validation is disabled, so wrong data might be sent if the Otter field is not properly set up based on the merge fields.
----
**Check if the tag in the Otter field MAPPED NAMED is sent to its corresponding tag in Mailchimp MERGE FIELDS.**
> [!NOTE]
> We only send the …
> feat: add merge fields for Mailchimp

- blocks.json
- inc/class-registration.php
- plugins/otter-pro/inc/class-main.php
- plugins/otter-pro/inc/css/blocks/class-modal-css.php
- plugins/otter-pro/inc/render/class-modal-block.php
- src/blocks/blocks/index.js
- src/blocks/blocks/modal/block.json
- src/blocks/blocks/modal/index.js
- src/blocks/blocks/modal/save.js
- src/blocks/blocks/popup/editor.scss
- src/blocks/blocks/popup/style.scss
- src/blocks/frontend/popup/index.js
- src/blocks/test/e2e/blocks/modal.spec.js
- src/dashboard/components/pages/Blocks.js
- src/pro/blocks/index.js
- src/pro/blocks/modal/block.json
- src/pro/blocks/modal/edit.js
- src/pro/blocks/modal/index.js
- src/pro/blocks/modal/inspector.js
- src/pro/blocks/modal/save.js
- src/pro/blocks/modal/types.d.ts
Closes https://github.com/Codeinwp/otter-internals/issues/175
The same features like Popup except for Popup Settings tabs in the Inspector
The `save` function of the modal saves only the inner content. The complete HTML structure is done via PHP, which overrides the default saving data. 
This method ensures that the modal is working under a valid license while keeping the original data safe. 
https://github.com/user-attachments/assets/23ff20c7-f2df-4a55-b9f3-47d7288f063e
----
> [!NOTE]
> This is PRO block, you will need Otter Pro
Modal is a popup with only the anchor option.
1. Insert a button and set an anchor
2. Insert a modal with the anche for the button
3. Check if it works like in the video.
----
> Add Modal Block

- package-lock.json
- package.json
Closes https://github.com/Codeinwp/otter-blocks/issues/2349
The current version of our react scripts requires a new react package that contains the new runtime for React 19. This is present only on WP 6.6 or higher. Our script loading was ignored because of the missing package in the early versions. 
I downgraded and pinned the `@wordpress/scrips` to the latest version that supports WP 6.5 or earlier. Now, the build files should be working fine.
Reference: https://github.com/WordPress/gutenberg/blob/2cbba93a29600f09f6f95c09f690576b90e79e9f/packages/scripts/CHANGELOG.md#2800-2024-05-31
----
Test if everything is working fine with the latest WP version and WP 6.5
----
> fix: pin down `@wordpress/script` to support WordPress 6.5 or earlier

- src/blocks/blocks/popup/save.js
- src/blocks/frontend/popup/popup.ts
Fix popup dismiss issue with recurring visitors option
Closes https://github.com/Codeinwp/otter-internals#228
In this PR I've fixed the popup dismiss issue with recurring visitors option.
> Fixed popup dismiss issue with recurring visitors option

- inc/class-main.php
Closes #2371
In this PR, I’ve addressed and resolved a fatal error that was occurring with PHP 8 for a specific edge case.
> Fixed PHP fatal error

- src/blocks/plugins/conditions/edit.js
Closes https://github.com/Codeinwp/otter-internals/issues/232
- The conditions help labels did not have the text domain like other strings
----
> fix: missing translations

- plugins/otter-pro/inc/plugins/class-patterns.php
- src/blocks/plugins/patterns-library/library.js
- tests/test-patterns-class.php
Closes https://github.com/Codeinwp/templates-cloud/issues/82
Swap the title of the registered pattern with its translated version if available. 
----
> feat: use translation in block patterns

- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/style.scss
Closes https://github.com/Codeinwp/otter-blocks/issues/2429
Added whitespace support
> Added whitespace support to form's submit button

- src/blocks/plugins/patterns-library/library.js
Closes #2456.
change Otter Patterns button order & Premium Designs appearance
----
- Open the otter patterns modal in the free version;
- The Premium Designs button should have a folder icon and the external link icon after the text;
----
> chore: change Otter Patterns button order & Premium Designs appearance

- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/style.scss
Closes https://github.com/Codeinwp/otter-blocks/issues/2457
In this PR, I've fixed the post images issue with the latest version of WordPress.
> Fixed post images with WP 6.7

- plugins/otter-pro/otter-pro.php
Issue https://github.com/Codeinwp/themeisle/issues/1676
Added the following filter to hide the SDK promo notice.
`add_filter( 'themeisle_sdk_ran_promos', '__return_true' );`
> Hide SDK random promo notice

- inc/plugins/class-dashboard.php
- otter-blocks.php
- plugins/otter-pro/inc/server/class-dashboard-server.php
- src/dashboard/components/LicenseField.js
- src/dashboard/index.js
- tests/php/static-analysis-stubs/otter.php
Closes https://github.com/Codeinwp/themeisle/issues/1687
- Add internal pages.
- Load survey via internal pages.
- Always use a masked license key on the dashboard.
----
Use https://github.com/Codeinwp/themeisle-sdk-main/pull/287 then go to Otter dashboard with this URL `/wp-admin/admin.php?page=otter&formbricksDebug=true` then check the Console
----
> feat: load Formbricks survey via internal pages hooks

- src/animation/frontend/count/index.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2559
I've fixed the delay and speed settings in the count animation.
> Fixed count animation delay and speed

- inc/integrations/class-form-settings-data.php
- inc/plugins/class-options-settings.php
- inc/server/class-form-server.php
- plugins/otter-pro/inc/plugins/class-form-pro-features.php
- src/blocks/blocks/form/edit.js
- src/blocks/blocks/form/inspector.js
- src/blocks/blocks/form/type.d.ts
- src/blocks/test/e2e/blocks/form.spec.js
Closes https://github.com/Codeinwp/otter-internals/issues/255.
This adds a From Field option to Form Block. This allows user to replace the default Admin Email when the emails are sent, to the admin or from the Autoresponder.
Keep in mind that this option might always work if the user is using an SMTP plugin that tend to override it.
----
- Make sure the From Email is reflected properly on sent emails.
----
> feat: add from field to Form Block

- inc/class-main.php
- inc/render/class-posts-grid-block.php
- src/blocks/blocks/posts/edit.js
- src/blocks/blocks/posts/inspector.js
- src/blocks/components/panel-tab/index.js
- src/blocks/components/typography-selector-control/editor.scss
- src/blocks/components/typography-selector-control/index.tsx
- src/blocks/plugins/conditions/edit.js
- src/dashboard/components/pages/Dashboard.js
Closes https://github.com/Codeinwp/otter-internals/issues/258, https://github.com/Codeinwp/otter-blocks/issues/2575, https://github.com/Codeinwp/otter-blocks/issues/2112, https://github.com/Codeinwp/otter-blocks/issues/2557.
This PR addresses various small fixes, which are:
- Auto-open newly added rule tab in Block Conditions
- Add “Random” Sort Option to Otter Posts Block
- Letter Case overlapping in the Sidebar
- Disabling Patterns Library doesn't hide patterns
- Make sure each issue is fixed. For Pattern Library, we only changed the description.
----
> feat: auto-open block conditions, random sort in posts and more

- inc/class-registration.php
- inc/plugins/class-dashboard.php
- inc/plugins/class-template-cloud.php
- src/blocks/plugins/options/index.js
- src/blocks/plugins/patterns-library/library.js
- src/dashboard/components/pages/Integrations.js
Closes https://github.com/Codeinwp/otter-internals/issues/251.
If you're a new user of Otter or an existing users who have never used the Cloud Library issue, the feature will not appear.
If you're an existing user who is using the feature or has used it in the past, it should continue to work the same way.
----
- Make sure the Cloud Patterns options appear in Settings and Patterns Modal based on if the user is new or existing.
---- 
- [] Visual elements are not affected by independent changes.
> feat: show cloud library only if the user has/had used it

- inc/class-registration.php
- inc/render/class-review-block.php
- plugins/otter-pro/otter-pro.php
- src/animation/editor.js
- src/animation/frontend.js
- src/blocks/blocks/popup/style.scss
- src/blocks/blocks/slider/style.scss
- src/blocks/frontend/slider/index.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2230, https://github.com/Codeinwp/otter-blocks/issues/2030, https://github.com/Codeinwp/otter-blocks/issues/2090, https://github.com/Codeinwp/otter-blocks/issues/2280, https://github.com/Codeinwp/otter-blocks/issues/2403, https://github.com/Codeinwp/otter-blocks/issues/2430.
- Fixes issue with Review Block generating schema twice in some cases. Fix tested on https://themeisle.com/blog/wp-engine-review-for-wordpress/ already.
- Fixes issue with Otter Pro trying to install Otter Blocks again if it was inactive
- Fixes Popup not showing top-padding
- Fixes issue with Slider Block arrows not having aria-label.
- Fixes SVG background appearing to be flickering
- Fixes decimal second values not working for Animation delay/speed
- Make sure …
> fix: Review block generating schema twice, and other smaller fixes

- inc/class-registration.php
- inc/plugins/class-dashboard.php
- src/blocks/plugins/menu-icons/inline.scss
- src/pro/plugins/posts/index.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2011, https://github.com/Codeinwp/otter-blocks/issues/2357.
- Fixes issue with FSE menu's font changing with Menu Icons
- Adds Date/Time/DateTime field from ACF to Posts Block
----
> fix: menu icon fonts and date time field in ACF

- inc/class-registration.php
- inc/plugins/class-dashboard.php
- inc/render/class-posts-grid-block.php
- src/blocks/index.js
- src/dashboard/components/Main.js
- src/dashboard/components/WelcomeNotice.js
- src/dashboard/style.scss
Closes https://github.com/Codeinwp/otter-internals/issues/249, https://github.com/Codeinwp/otter-internals/issues/248, https://github.com/Codeinwp/otter-blocks/issues/2489.
- Trigger Formbricks in the Block Editor after a block from Otter collection has been added. You can see the script being triggered in the console.
- Adds a welcome notice to Dashboard once you activate Otter and automatically redirected to Dashboard.
- Fixes the pagination issue in Homepage.
----
- For pagination, make sure it works in Homepage and also works in Page/Posts with and without pretty permalinks.
----
> feat: trigget formbricks in the editor, add welcome notice and fix pagination

- src/blocks/blocks/section/column/edit.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2335.
This fixes the issue with mobile/tablet settings not previewing the column size change in the editor. Here's a video from Ionut on how to reproduce the issue: https://www.loom.com/share/48fa2cadde5846bfaf539e360b52442f?from_recorder=1&focus_title=1
----
Make sure the preview shows the correct size for their respective screen choice.
----
> fix: columns layout settings for the section block is not working for mobile & tablet in the editor

- src/pro/blocks/modal/edit.js
Closes https://github.com/Codeinwp/otter-blocks/issues/2616
I have fixed the media upload height for the modal block.
> Fixed media upload height

- inc/server/class-dynamic-content-server.php
Closes https://github.com/Codeinwp/otter-internals/issues/259
Prevent unauthenticated users from requesting the API.
> fix: prevent unauthenticated request
